#!/usr/bin/env bash

# Shared font-sync helpers.
#
# Callers may source runtime/init.bash first, but these helpers also lazily
# load it when they need layered config access.

font_sync_ensure_runtime() {
  if declare -F hypr_config_value_from_layers >/dev/null 2>&1; then
    return 0
  fi

  local lib_dir="${LIB_DIR:-$HOME/.local/lib}"
  # shellcheck source=/dev/null
  source "${lib_dir}/hypr/runtime/init.bash" || return 1
}

font_sync_resolve_font_value() {
  local kind="$1"
  local general_font=""
  local mono_font=""
  local bar_font=""
  local menu_font=""

  font_sync_ensure_runtime || return 1

  general_font="$(hypr_config_value_from_layers "FONT" 2>/dev/null || true)"
  mono_font="$(hypr_config_value_from_layers "MONOSPACE_FONT" 2>/dev/null || true)"
  bar_font="$(hypr_config_value_from_layers "BAR_FONT" 2>/dev/null || true)"
  menu_font="$(hypr_config_value_from_layers "MENU_FONT" 2>/dev/null || true)"

  mono_font="${mono_font:-monospace}"
  bar_font="${bar_font:-${general_font:-monospace}}"
  menu_font="${menu_font:-${general_font:-monospace}}"

  case "${kind}" in
    mono) printf '%s\n' "${mono_font}" ;;
    bar) printf '%s\n' "${bar_font}" ;;
    menu) printf '%s\n' "${menu_font}" ;;
    *) return 1 ;;
  esac
}

font_sync_write_waybar_font_include_if_changed() {
  local font_family="$1"
  local include_dir="${2:-${XDG_CONFIG_HOME:-$HOME/.config}/waybar/includes}"
  local target_file="${include_dir}/font.css"
  local tmp_file=""

  mkdir -p "${include_dir}"
  tmp_file="$(mktemp "${target_file}.tmp.XXXXXX")" || return 1

  cat > "${tmp_file}" <<EOF
/* Generated by: hyprshell fonts/font-sync.sh
 * Source: \$XDG_DATA_HOME/hypr/variables.conf
 */

* {
  font-family: "${font_family}","Symbols Nerd Font","Noto Color Emoji",monospace;
}
EOF

  if [[ -f "${target_file}" ]] && cmp -s "${tmp_file}" "${target_file}"; then
    rm -f "${tmp_file}"
    return 0
  fi

  mv -f "${tmp_file}" "${target_file}"
}

font_sync_apply_waybar_bar_font_include() {
  local bar_font="${1:-}"
  local include_dir="${2:-}"

  if [[ -z "${bar_font}" ]]; then
    bar_font="$(font_sync_resolve_font_value "bar")" || return 1
  fi

  font_sync_write_waybar_font_include_if_changed "${bar_font}" "${include_dir}"
}
