#!/usr/bin/env bash

set -euo pipefail

if [[ "${HYPR_SHELL_INIT:-0}" -ne 1 ]]; then
  eval "$(hyprshell init)"
fi

menu_from=""
menu_to=""
bar_to=""
rofi_to=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --menu-from)
      menu_from="${2:-}"; shift 2 ;;
    --menu-to)
      menu_to="${2:-}"; shift 2 ;;
    --bar-to)
      bar_to="${2:-}"; shift 2 ;;
    --rofi-to)
      rofi_to="${2:-}"; shift 2 ;;
    -h|--help)
      cat <<'EOF'
Usage: hyprshell fonts/font-sync.sh [--menu-from OLD] [--menu-to NEW] [--bar-to NEW]

Regenerates Waybar font include, and (optionally) rewrites Rofi font-family
strings in *.rasi from OLD -> NEW while keeping existing sizes.
EOF
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

bar_font="${bar_to:-$(hyprshell fonts/font-get.sh bar)}"
menu_font="${menu_to:-$(hyprshell fonts/font-get.sh menu)}"

# -----------------------------------------------------------------------------
# Waybar: generated include
# -----------------------------------------------------------------------------

waybar_include_dir="$HOME/.config/waybar/includes"
mkdir -p "${waybar_include_dir}"

cat > "${waybar_include_dir}/font.css" <<EOF
/* Generated by: hyprshell fonts/font-sync.sh
 * Source: ${HOME}/.config/hypr/variables.conf
 */

* {
  font-family: "${bar_font}","Symbols Nerd Font","Noto Color Emoji",monospace;
}
EOF

# -----------------------------------------------------------------------------
# Rofi: rewrite OLD -> NEW inside quoted font strings
# -----------------------------------------------------------------------------

if command -v python3 >/dev/null 2>&1; then
  if [[ -n "${menu_from}" && -n "${menu_to}" && "${menu_from}" != "${menu_to}" ]]; then
    MENU_FROM="${menu_from}" MENU_TO="${menu_to}" python3 - <<'PY'
import os
from pathlib import Path

menu_from = os.environ.get("MENU_FROM", "")
menu_to = os.environ.get("MENU_TO", "")
root = Path.home() / ".config" / "rofi"

if not menu_from or not menu_to or not root.exists():
    raise SystemExit(0)

needle = f"\"{menu_from} "
repl = f"\"{menu_to} "

for path in root.rglob("*.rasi"):
    try:
        original = path.read_text(encoding="utf-8")
    except Exception:
        continue
    updated = original.replace(needle, repl)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
PY
  fi

  if [[ -n "${rofi_to}" ]]; then
    ROFI_TO="${rofi_to}" python3 - <<'PY'
import os
import re
from pathlib import Path

rofi_to = (os.environ.get("ROFI_TO") or "").strip()
root = Path.home() / ".config" / "rofi"

if not rofi_to or not root.exists():
    raise SystemExit(0)

exclude_tokens = [
    "feather",
    "fontawesome",
    "font awesome",
    "material",
    "symbols nerd font",
    "noto color emoji",
]

pattern = re.compile(r'^(\s*font\s*:\s*")([^"\n]+?)(\s+)(\d+)("\s*;)', re.M)

for path in root.rglob("*.rasi"):
    try:
        original = path.read_text(encoding="utf-8")
    except Exception:
        continue

    def repl(m: re.Match) -> str:
        family = m.group(2).strip()
        family_lower = family.lower()
        if any(tok in family_lower for tok in exclude_tokens):
            return m.group(0)
        size = m.group(4)
        return f'{m.group(1)}{rofi_to}{m.group(3)}{size}{m.group(5)}'

    updated = pattern.sub(repl, original)
    if updated != original:
        path.write_text(updated, encoding="utf-8")
PY
  fi
fi
