#!/usr/bin/env bash
# Sourced module; strict mode is owned by the entrypoint.

# Shared font-sync helpers.
#
# Callers may source runtime/init.bash first, but these helpers also lazily
# load it when they need layered config access.

font_sync_ensure_runtime() {
  if declare -F hypr_config_value_from_layers >/dev/null 2>&1; then
    return 0
  fi

  local lib_dir="${LIB_DIR:-$HOME/.local/lib}"
  # shellcheck source=/dev/null
  source "${lib_dir}/hypr/runtime/init.bash" || return 1
}

font_sync_resolve_font_value() {
  local kind="$1"
  local general_font=""
  local mono_font=""
  local bar_font=""
  local bar_icon_font=""
  local menu_font=""

  font_sync_ensure_runtime || return 1

  case "${kind}" in
    mono)
      mono_font="$(hypr_config_value_from_layers "MONOSPACE_FONT" 2>/dev/null || true)"
      printf '%s\n' "${mono_font:-monospace}"
      ;;
    bar)
      bar_font="$(hypr_config_value_from_layers "BAR_FONT" 2>/dev/null || true)"
      if [[ -z "${bar_font}" ]]; then
        general_font="$(hypr_config_value_from_layers "FONT" 2>/dev/null || true)"
        bar_font="${general_font:-monospace}"
      fi
      printf '%s\n' "${bar_font}"
      ;;
    bar-icon)
      bar_icon_font="$(hypr_config_value_from_layers "BAR_ICON_FONT" 2>/dev/null || true)"
      printf '%s\n' "${bar_icon_font:-CaskaydiaCove Nerd Font}"
      ;;
    menu)
      menu_font="$(hypr_config_value_from_layers "MENU_FONT" 2>/dev/null || true)"
      if [[ -z "${menu_font}" ]]; then
        general_font="$(hypr_config_value_from_layers "FONT" 2>/dev/null || true)"
        menu_font="${general_font:-monospace}"
      fi
      printf '%s\n' "${menu_font}"
      ;;
    *) return 1 ;;
  esac
}

font_sync_write_waybar_font_include_if_changed() {
  local font_family="$1"
  local icon_font_family="${2:-}"
  local include_dir="${3:-${XDG_CONFIG_HOME:-$HOME/.config}/waybar/includes}"
  local target_file="${include_dir}/font.css"
  local tmp_file=""

  if [[ -z "${icon_font_family}" ]]; then
    icon_font_family="$(font_sync_resolve_font_value "bar-icon" 2>/dev/null || true)"
    icon_font_family="${icon_font_family:-CaskaydiaCove Nerd Font}"
  fi

  mkdir -p "${include_dir}"
  tmp_file="$(mktemp "${target_file}.tmp.XXXXXX")" || return 1

  cat > "${tmp_file}" <<EOF
/* Generated by: hyprshell fonts/font-sync.sh
 * Source: layered Hypr font config
 */

* {
  font-family: "${font_family}","${icon_font_family}","Noto Color Emoji",monospace;
}
EOF

  if [[ -f "${target_file}" ]] && cmp -s "${tmp_file}" "${target_file}"; then
    rm -f "${tmp_file}"
    return 0
  fi

  mv -f "${tmp_file}" "${target_file}"
}

font_sync_apply_waybar_bar_font_include() {
  local bar_font="${1:-}"
  local icon_font="${2:-}"
  local include_dir="${3:-}"

  if [[ -z "${bar_font}" ]]; then
    bar_font="$(font_sync_resolve_font_value "bar")" || return 1
  fi

  if [[ -z "${icon_font}" ]]; then
    icon_font="$(font_sync_resolve_font_value "bar-icon" 2>/dev/null || true)"
  fi

  font_sync_write_waybar_font_include_if_changed "${bar_font}" "${icon_font}" "${include_dir}"
}
