#!/usr/bin/env bash
set -euo pipefail

LAYOUTS=("dwindle" "master" "scrolling" "monocle")
declare -A LAYOUT_ICONS=(
  ["dwindle"]="󰕴"
  ["master"]="󱂩"
  ["scrolling"]="󰮳"
  ["monocle"]="󰁌"
)
declare -A LAYOUT_LABELS=(
  ["dwindle"]="Dwindle"
  ["master"]="Master"
  ["scrolling"]="Scrolling"
  ["monocle"]="Monocle"
)

STATE_FILE="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}/window-layout.lua"

show_help() {
  cat <<'HELP'
Usage: window-layout.sh [--toggle|--toggle-reverse|--set <name>|--waybar|--help]

  --toggle           Cycle to the next layout
  --toggle-reverse   Cycle to the previous layout
  --set <name>       Apply a specific layout
  --waybar           Emit JSON for the waybar custom module
HELP
}

current_layout() {
  hyprctl getoption general:layout -j 2>/dev/null \
    | sed -n 's/.*"str":[[:space:]]*"\([^"]*\)".*/\1/p'
}

apply_layout() {
  local name="$1"
  mkdir -p "$(dirname "${STATE_FILE}")"
  cat >"${STATE_FILE}" <<LUA
-- Generated by window-layout.sh. Do not edit manually.
hl.config({general = {layout = "${name}"}})
LUA
  hyprctl reload config-only -q
}

step_layout() {
  local current="$1" step="$2" count=${#LAYOUTS[@]} i
  for i in "${!LAYOUTS[@]}"; do
    if [[ "${LAYOUTS[$i]}" == "${current}" ]]; then
      printf '%s\n' "${LAYOUTS[$(((i + step + count) % count))]}"
      return
    fi
  done
  printf '%s\n' "${LAYOUTS[0]}"
}

handle_toggle() {
  apply_layout "$(step_layout "$(current_layout)" "${1:-1}")"
}

handle_set() {
  [[ -v LAYOUT_ICONS[$1] ]] || { printf 'unknown layout: %s\n' "$1" >&2; exit 1; }
  apply_layout "$1"
}

handle_waybar() {
  local name icon label
  name="$(current_layout)"
  [[ -v LAYOUT_ICONS[$name] ]] || name="${LAYOUTS[0]}"
  icon="${LAYOUT_ICONS[$name]}"
  label="${LAYOUT_LABELS[$name]}"
  printf '{"text": "%s", "tooltip": "Layout: %s %s", "class": "custom-window-layout"}\n' \
    "${icon}" "${icon}" "${label}"
}

case "${1:-}" in
  --toggle) handle_toggle 1 ;;
  --toggle-reverse) handle_toggle -1 ;;
  --set)
    shift
    [[ $# -gt 0 ]] || { printf 'Error: --set requires a layout name\n' >&2; exit 1; }
    handle_set "$1"
    ;;
  --waybar) handle_waybar ;;
  -h | --help | "") show_help ;;
  *) printf 'Unknown option: %s\n' "$1" >&2; show_help >&2; exit 1 ;;
esac
