# Shared Hyprland core
# Stock-only layer sourced by $XDG_CONFIG_HOME/hypr/hyprland.conf.

$HYPR_SHARED_CORE = 1

# Shared core layer
source = $XDG_DATA_HOME/hypr/variables.conf
source = $XDG_DATA_HOME/hypr/defaults.conf
source = $XDG_DATA_HOME/hypr/env.conf
source = $XDG_DATA_HOME/hypr/dynamic.conf

# hyprlang if SCREEN_SHADER_COMPILED
decoration:screen_shader = $SCREEN_SHADER_COMPILED
# hyprlang endif

source = $XDG_DATA_HOME/hypr/startup.conf
