# Shared Hyprland core
# Stock-only layer sourced by ~/.config/hypr/hyprland.conf.

$HYPR_SHARED_CORE = 1

# Shared core layer
source = $HOME/.local/share/hypr/variables.conf
source = $HOME/.local/share/hypr/defaults.conf
source = $HOME/.local/share/hypr/env.conf
source = $HOME/.local/share/hypr/dynamic.conf

# hyprlang if SCREEN_SHADER_COMPILED
decoration:screen_shader = $SCREEN_SHADER_COMPILED
# hyprlang endif

source = $HOME/.local/share/hypr/startup.conf
