$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta
$ICON_THEME = Tela-circle-solarized
$COLOR_SCHEME = prefer-dark
$CURSOR_THEME = capitaine-cursors-light
$CURSOR_SIZE = 30
$NVIM_SCHEME = solarized
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$FONT = DejaVuSansM Nerd Font
$BAR_FONT = DejaVuSansM Nerd Font
$MENU_FONT = DejaVuSansM Nerd Font
$MONOSPACE_FONT = DejaVuSansM Nerd Font
$TERMINAL_FONT = DejaVuSansM Nerd Font
$NOTIFICATION_FONT = DejaVuSansM Nerd Font Mono

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(b58900ff)
    col.inactive_border = rgba(93a1a1cc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(b58900ff)
    col.border_inactive = rgba(93a1a1cc)
    col.border_locked_active = rgba(b58900ff)
    col.border_locked_inactive = rgba(93a1a1cc)
}

decoration {
    rounding = 4

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = false
    }
}
