[colors.primary]
background = "#ffffff"
foreground = "#0a0a0a"

[colors.cursor]
text = "#ffffff"
cursor = "#000000"

[colors.selection]
text = "#0a0a0a"
background = "#0a0a0a"

[colors.normal]
black = "#ffffff"
red = "#0a0a0a"
green = "#0a0a0a"
yellow = "#0a0a0a"
blue = "#0a0a0a"
magenta = "#0a0a0a"
cyan = "#0a0a0a"
white = "#0a0a0a"

[colors.bright]
black = "#919191"
red = "#0a0a0a"
green = "#0a0a0a"
yellow = "#0a0a0a"
blue = "#0a0a0a"
magenta = "#0a0a0a"
cyan = "#0a0a0a"
white = "#000000"
