$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Fluent-grey
$COLOR_SCHEME = prefer-light
$NVIM_SCHEME = pywal
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = Emo
$CURSOR_SIZE = 30

general {
    gaps_in = 5
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(0a0a0aff)
    col.inactive_border = rgba(919191cc)
}

group {
    col.border_active = rgba(0a0a0aff)
    col.border_inactive = rgba(919191cc)
    col.border_locked_active = rgba(0a0a0aff)
    col.border_locked_inactive = rgba(919191cc)
}

decoration {
    rounding = 0
    active_opacity = 1
    inactive_opacity = 1
    shadow:enabled = false

    blur {
        enabled = false
    }
}
