background = "#ffffff"
foreground = "#0a0a0a"
cursor-color = "#000000"
cursor-text = "#ffffff"
selection-foreground = "#000000"
selection-background = "#f7f7f7"

colors = [
  "#ffffff",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#919191",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#0a0a0a",
  "#000000",
]
