$HOME/.config/alacritty/theme.toml

[colors.primary]
background = "#1B1B1B"
foreground = "#efebdc"

[colors.cursor]
text = "#1B1B1B"
cursor = "#C0AF7F"

[colors.selection]
text = "#1B1B1B"
background = "#e75a50"

[colors.search.matches]
foreground = "#1B1B1B"
background = "#E1CE98"

[colors.footer_bar]
foreground = "#efebdc"
background = "#323232"

[colors.normal]
black = "#1B1B1B"
red = "#F44336"
green = "#e75a50"
yellow = "#a99b7a"
blue = "#e58980"
magenta = "#77838a"
cyan = "#6d6d6d"
white = "#E1CE98"

[colors.bright]
black = "#817f68"
red = "#e75a50"
green = "#77838a"
yellow = "#a99b7a"
blue = "#e58980"
magenta = "#9ba2a6"
cyan = "#888888"
white = "#efebdc"
