$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Beauty-yellow-dark
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = aether
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = capitaine-cursors-light
$CURSOR_SIZE = 30
$FONT = JetBrainsMono Nerd Font
$BAR_FONT = JetBrainsMono Nerd Font
$MENU_FONT = JetBrainsMono Nerd Font
$MONOSPACE_FONT = JetBrainsMono Nerd Font
$TERMINAL_FONT = JetBrainsMono Nerd Font
$NOTIFICATION_FONT = JetBrainsMono Nerd Font Mono

general {
    col.active_border = rgba(a99b7aee) rgba(1B1B1Bee) rgba(1B1B1Bee) rgba(a99b7aee) 5deg
    col.inactive_border = rgb(1B1B1B)
    gaps_in = 4
    gaps_out = 5
    border_size = 2
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(e75a50ee) rgba(1B1B1Bee) rgba(1B1B1Bee) rgba(e75a50ee) 5deg
    col.border_inactive = rgb(1B1B1B)

    groupbar {
        col.active = rgba(e75a5088)
        col.inactive = rgba(1B1B1Baa)
        text_color = rgb(efebdc)
        text_color_inactive = rgba(a99b7aaa)
    }
}

decoration {
    rounding = 3
    rounding_power = 3
    shadow {
        enabled = yes
        range = 16
        color = rgba(00000052)
    }
    blur {
        enabled = true
        size = 2
        passes = 2
        special = true
        brightness = 0.40
        contrast = 0.75
    }
}
