$HOME/.config/rofi/theme.rasi
* {
    background:            #282c34e6;
    background-alpha:    #282c3459;
    foreground:            #979eabff;
    border:            #61afefff;
    accent:            #c678ddff;
    selected-background:          #61afefff;
    selected-foreground:          #495495ff;
    separator:           #80808080;
    urgent:              #e06c75ff;
    active:              #98c379ff;
}
