#!/usr/bin/env bash
# shellcheck disable=SC2154
#
# color.files.sh - Palette loading and file materialization helpers

load_theme_palette() {
  local theme_file="${1}"
  [[ -r "${theme_file}" ]] || return 1

  THEME_BG="$(awk '$1=="background"{print $2; exit}' "${theme_file}")"
  THEME_FG="$(awk '$1=="foreground"{print $2; exit}' "${theme_file}")"
  THEME_CURSOR="$(awk '$1=="cursor"{print $2; exit}' "${theme_file}")"

  local i key val
  THEME_COLORS=()
  for i in {0..15}; do
    key="color${i}"
    val="$(awk -v key="${key}" '$1==key{print $2; exit}' "${theme_file}")"
    [[ "${val}" =~ ^#[0-9A-Fa-f]{6}$ ]] || val=""
    THEME_COLORS[$i]="${val}"
  done

  for i in {0..15}; do
    [[ -n "${THEME_COLORS[$i]}" ]] || return 1
  done

  [[ "${THEME_BG}" =~ ^#[0-9A-Fa-f]{6}$ ]] || THEME_BG="${THEME_COLORS[0]}"
  [[ "${THEME_FG}" =~ ^#[0-9A-Fa-f]{6}$ ]] || THEME_FG="${THEME_COLORS[15]}"
  [[ "${THEME_CURSOR}" =~ ^#[0-9A-Fa-f]{6}$ ]] || THEME_CURSOR="${THEME_FG}"
  return 0
}

write_wal_theme_file() {
  local out_file="$1"
  local tmp_file="${out_file}.tmp.$$"

  mkdir -p "$(dirname "${out_file}")"

  cat >"${tmp_file}" <<JSON
{
  "special": {
    "background": "${THEME_BG}",
    "foreground": "${THEME_FG}",
    "cursor": "${THEME_CURSOR}"
  },
  "colors": {
    "color0": "${THEME_COLORS[0]}",
    "color1": "${THEME_COLORS[1]}",
    "color2": "${THEME_COLORS[2]}",
    "color3": "${THEME_COLORS[3]}",
    "color4": "${THEME_COLORS[4]}",
    "color5": "${THEME_COLORS[5]}",
    "color6": "${THEME_COLORS[6]}",
    "color7": "${THEME_COLORS[7]}",
    "color8": "${THEME_COLORS[8]}",
    "color9": "${THEME_COLORS[9]}",
    "color10": "${THEME_COLORS[10]}",
    "color11": "${THEME_COLORS[11]}",
    "color12": "${THEME_COLORS[12]}",
    "color13": "${THEME_COLORS[13]}",
    "color14": "${THEME_COLORS[14]}",
    "color15": "${THEME_COLORS[15]}"
  }
}
JSON

  mv -f "${tmp_file}" "${out_file}"
}

resolve_wallpaper_fallback() {
  local cache_wall="${XDG_CACHE_HOME:-$HOME/.cache}/hypr/wallpaper/current/wall.set"
  if [[ -e "${cache_wall}" ]]; then
    readlink -f "${cache_wall}" 2>/dev/null && return 0
  fi

  local theme_wall="${HYPR_THEME_DIR}/wall.set"
  if [[ -e "${theme_wall}" ]]; then
    readlink -f "${theme_wall}" 2>/dev/null && return 0
  fi

  return 1
}

compute_template_hash() {
  local template_dir="${XDG_CONFIG_HOME:-$HOME/.config}/wal/templates"
  local hash_cmd="${HYPR_HASH_COMMAND:-sha1sum}"
  local raw_hash

  [[ -d "${template_dir}" ]] || return 0
  command -v "${hash_cmd}" &>/dev/null || hash_cmd="sha1sum"
  command -v "${hash_cmd}" &>/dev/null || return 0

  raw_hash="$({
    find "${template_dir}" -type f -print0 2>/dev/null \
      | sort -z \
      | xargs -0 "${hash_cmd}" 2>/dev/null \
      | "${hash_cmd}" 2>/dev/null \
      | awk '{print $1}'
  })"
  [[ -n "${raw_hash}" ]] && template_hash_suffix="_tpl${raw_hash:0:12}"
}

generate_hypr_colors_from_theme() {
  local kitty_theme_file="${HYPR_THEME_DIR}/kitty.theme"
  local out_file="${HOME}/.config/hypr/themes/colors.conf"
  local tmp_file="${out_file}.tmp.$$"

  [[ -n "${HYPR_THEME_DIR}" ]] || return 1
  [[ -r "${kitty_theme_file}" ]] || {
    print_log -sec "theme" -warn "colors" "missing kitty.theme: ${kitty_theme_file}"
    return 1
  }

  if ! load_theme_palette "${kitty_theme_file}"; then
    print_log -sec "theme" -warn "colors" "incomplete palette in ${kitty_theme_file}"
    return 1
  fi

  local -a theme_colors=()
  local i
  for i in {0..15}; do
    theme_colors[$i]="${THEME_COLORS[$i]}"
  done

  local theme_bg="${THEME_BG}"
  local theme_fg="${THEME_FG}"
  local active_border inactive_border_bg inactive_border_fg
  active_border="${theme_colors[4]#\#}ff"
  inactive_border_bg="${theme_colors[0]#\#}cc"
  inactive_border_fg="${theme_colors[8]#\#}cc"

  mkdir -p "$(dirname "${out_file}")"
  [[ -L "${out_file}" ]] && rm -f "${out_file}"

  {
    echo "# Autogenerated theme colors (from kitty.theme)"
    echo "# Theme: ${HYPR_THEME}"
    echo "# Source: ${kitty_theme_file}"
    echo
    echo "# Standard theme colors"
    for i in {0..15}; do
      printf '\$color%s = %s\n' "${i}" "${theme_colors[$i]}"
    done
    echo
    echo "# Hyprland-friendly helpers (no leading '#')"
    for i in {0..15}; do
      local hex="${theme_colors[$i]#\#}"
      printf '\$color%see = %s\n' "${i}" "${hex}ee"
    done
    echo
    printf '\$background = %s\n' "${theme_bg}"
    printf '\$foreground = %s\n' "${theme_fg}"
    printf '\$cursor = %s\n' "${theme_fg}"
    echo
    cat <<EOF_INNER

general {
    col.active_border = rgba(${active_border}) rgba(${active_border}) 45deg
    col.inactive_border = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
}

group {
    col.border_active = rgba(${active_border}) rgba(${active_border}) 45deg
    col.border_inactive = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
    col.border_locked_active = rgba(${active_border}) rgba(${active_border}) 45deg
    col.border_locked_inactive = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
}
EOF_INNER
  } >"${tmp_file}"

  mv -f "${tmp_file}" "${out_file}"
  print_log -sec "theme" -stat "colors" "wrote ${out_file}"
}

_safe_hyq_get() {
  local hyq_output="$1"
  local var_name="$2"
  local value
  value=$(echo "${hyq_output}" | grep "^__${var_name}=" | head -1 | sed 's/^__[A-Z_]*=//' | tr -d '"')
  if [[ "${value}" =~ \$\(|\`|\; ]]; then
    print_log -sec "hyq" -warn "security" "blocked unsafe value for ${var_name}"
    return 1
  fi
  echo "${value}"
}
