#!/usr/bin/env bash
# shellcheck disable=SC2154
#
# color.files.sh - Palette loading and file materialization helpers

load_theme_palette() {
  local theme_file="${1}"
  local bg_name="$2" fg_name="$3" cursor_name="$4" colors_name="$5"
  local -n bg_ref="$bg_name" fg_ref="$fg_name" cursor_ref="$cursor_name" colors_ref="$colors_name"
  local key="" val="" line="" i
  local -A seen=()
  [[ -r "${theme_file}" ]] || return 1

  bg_ref=""
  fg_ref=""
  cursor_ref=""
  colors_ref=()

  while IFS= read -r line || [[ -n "${line}" ]]; do
    read -r key val _ <<< "${line}"
    [[ -n "${key}" && -n "${val}" ]] || continue
    [[ -v "seen[${key}]" ]] && continue

    case "${key}" in
      background)
        bg_ref="${val}"
        seen["${key}"]=1
        ;;
      foreground)
        fg_ref="${val}"
        seen["${key}"]=1
        ;;
      cursor)
        cursor_ref="${val}"
        seen["${key}"]=1
        ;;
      color[0-9] | color1[0-5])
        [[ "${val}" =~ ^#[0-9A-Fa-f]{6}$ ]] || val=""
        colors_ref[${key#color}]="${val}"
        seen["${key}"]=1
        ;;
    esac
  done < "${theme_file}"

  for i in {0..15}; do
    [[ -n "${colors_ref[$i]}" ]] || return 1
  done

  [[ "${bg_ref}" =~ ^#[0-9A-Fa-f]{6}$ ]] || bg_ref="${colors_ref[0]}"
  [[ "${fg_ref}" =~ ^#[0-9A-Fa-f]{6}$ ]] || fg_ref="${colors_ref[15]}"
  [[ "${cursor_ref}" =~ ^#[0-9A-Fa-f]{6}$ ]] || cursor_ref="${fg_ref}"
  return 0
}

write_wal_theme_file() {
  local out_file="$1"
  local theme_bg="$2" theme_fg="$3" theme_cursor="$4" theme_colors_name="$5"
  local -n theme_colors_ref="$theme_colors_name"
  local out_dir=""
  local tmp_file=""

  out_dir="$(dirname "${out_file}")"
  mkdir -p "${out_dir}"
  tmp_file="$(mktemp "${out_dir}/.$(basename "${out_file}").XXXXXX")" || return 1

  cat >"${tmp_file}" <<JSON
{
  "special": {
    "background": "${theme_bg}",
    "foreground": "${theme_fg}",
    "cursor": "${theme_cursor}"
  },
  "colors": {
    "color0": "${theme_colors_ref[0]}",
    "color1": "${theme_colors_ref[1]}",
    "color2": "${theme_colors_ref[2]}",
    "color3": "${theme_colors_ref[3]}",
    "color4": "${theme_colors_ref[4]}",
    "color5": "${theme_colors_ref[5]}",
    "color6": "${theme_colors_ref[6]}",
    "color7": "${theme_colors_ref[7]}",
    "color8": "${theme_colors_ref[8]}",
    "color9": "${theme_colors_ref[9]}",
    "color10": "${theme_colors_ref[10]}",
    "color11": "${theme_colors_ref[11]}",
    "color12": "${theme_colors_ref[12]}",
    "color13": "${theme_colors_ref[13]}",
    "color14": "${theme_colors_ref[14]}",
    "color15": "${theme_colors_ref[15]}"
  }
}
JSON

  mv -f "${tmp_file}" "${out_file}"
}

resolve_wallpaper_fallback() {
  local cache_wall="${XDG_CACHE_HOME:-$HOME/.cache}/hypr/wallpaper/current/wall.set"
  if [[ -e "${cache_wall}" ]]; then
    readlink -f "${cache_wall}" 2>/dev/null && return 0
  fi

  local theme_wall="${HYPR_THEME_DIR}/wall.set"
  if [[ -e "${theme_wall}" ]]; then
    readlink -f "${theme_wall}" 2>/dev/null && return 0
  fi

  return 1
}

compute_template_hash() {
  local template_dir="${XDG_CONFIG_HOME:-$HOME/.config}/wal/templates"
  local hash_cmd="${HYPR_HASH_COMMAND:-sha1sum}"
  local raw_hash

  [[ -d "${template_dir}" ]] || return 0
  command -v "${hash_cmd}" &>/dev/null || hash_cmd="sha1sum"
  command -v "${hash_cmd}" &>/dev/null || return 0

  raw_hash="$({
    find "${template_dir}" -type f -print0 2>/dev/null \
      | sort -z \
      | xargs -0 "${hash_cmd}" 2>/dev/null \
      | "${hash_cmd}" 2>/dev/null \
      | awk '{print $1}'
  })"
  [[ -n "${raw_hash}" ]] && template_hash_suffix="_tpl${raw_hash:0:12}"
}

generate_hypr_colors_from_theme() {
  local kitty_theme_file="${HYPR_THEME_DIR}/kitty.theme"
  local out_file="${HOME}/.config/hypr/themes/colors.conf"
  local out_dir=""
  local tmp_file=""
  local theme_bg="" theme_fg="" theme_cursor=""
  local -a theme_colors=()

  [[ -n "${HYPR_THEME_DIR}" ]] || return 1
  [[ -r "${kitty_theme_file}" ]] || {
    print_log -sec "theme" -warn "colors" "missing kitty.theme: ${kitty_theme_file}"
    return 1
  }

  if ! load_theme_palette "${kitty_theme_file}" theme_bg theme_fg theme_cursor theme_colors; then
    print_log -sec "theme" -warn "colors" "incomplete palette in ${kitty_theme_file}"
    return 1
  fi

  out_dir="$(dirname "${out_file}")"
  mkdir -p "${out_dir}"
  tmp_file="$(mktemp "${out_dir}/.$(basename "${out_file}").XXXXXX")" || return 1
  local i
  local active_border inactive_border_bg inactive_border_fg
  local display_theme_source="${kitty_theme_file}"
  active_border="${theme_colors[4]#\#}ff"
  inactive_border_bg="${theme_colors[0]#\#}cc"
  inactive_border_fg="${theme_colors[8]#\#}cc"
  [[ -n "${HOME:-}" ]] && display_theme_source="${display_theme_source/#${HOME}/\$HOME}"

  mkdir -p "$(dirname "${out_file}")"
  [[ -L "${out_file}" ]] && rm -f "${out_file}"

  {
    echo "# Autogenerated theme colors (from kitty.theme)"
    echo "# Theme: ${HYPR_THEME}"
    echo "# Source: ${display_theme_source}"
    echo
    echo "# Standard theme colors"
    for i in {0..15}; do
      printf '\$color%s = %s\n' "${i}" "${theme_colors[$i]}"
    done
    echo
    echo "# Hyprland-friendly helpers (no leading '#')"
    for i in {0..15}; do
      local hex="${theme_colors[$i]#\#}"
      printf '\$color%see = %s\n' "${i}" "${hex}ee"
    done
    echo
    printf '\$background = %s\n' "${theme_bg}"
    printf '\$foreground = %s\n' "${theme_fg}"
    printf '\$cursor = %s\n' "${theme_fg}"
    echo
    cat <<EOF_INNER

general {
    col.active_border = rgba(${active_border}) rgba(${active_border}) 45deg
    col.inactive_border = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
}

group {
    col.border_active = rgba(${active_border}) rgba(${active_border}) 45deg
    col.border_inactive = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
    col.border_locked_active = rgba(${active_border}) rgba(${active_border}) 45deg
    col.border_locked_inactive = rgba(${inactive_border_bg}) rgba(${inactive_border_fg}) 45deg
}
EOF_INNER
  } >"${tmp_file}"

  mv -f "${tmp_file}" "${out_file}"
  print_log -sec "theme" -stat "colors" "wrote ${out_file}"
}

_safe_hyq_get() {
  local hyq_output="$1"
  local var_name="$2"
  local value
  value=$(echo "${hyq_output}" | grep "^__${var_name}=" | head -1 | sed 's/^__[A-Z_]*=//' | tr -d '"')
  if [[ "${value}" =~ \$\(|\`|\; ]]; then
    print_log -sec "hyq" -warn "security" "blocked unsafe value for ${var_name}"
    return 1
  fi
  echo "${value}"
}
