$HOME/.config/rofi/theme.rasi
* {
    background:            #f8f5e4e6;
    background-alpha:    #f8f5e459;
    foreground:            #5c6a72ff;
    border:            #a6b0a0ff;
    accent:            #35a77cff;
    selected-background:          #2E6F40ff;
    selected-foreground:          #fffbefff;
    separator:           #80808080;
    urgent:              #f85552ff;
    active:              #8da101ff;
}
