#!/usr/bin/env bash

set -euo pipefail

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$dotfiles_dir/stow.purge.sh"
"$dotfiles_dir/stow.link.sh"
"$dotfiles_dir/stow.services.sh"

# Ensure Waybar includes file exists to avoid import errors on fresh setups.
xdg_config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
waybar_border_radius="${xdg_config_home}/waybar/includes/border-radius.css"
if [[ ! -f "$waybar_border_radius" ]]; then
  mkdir -p "$(dirname "$waybar_border_radius")"
  cat >"$waybar_border_radius" <<'EOF'
/*
This file is autogenerated.
*/

* {
  border-radius: 0pt;
}
EOF
fi

# Reload Hyprland config if running so changes take effect immediately.
if command -v hyprctl >/dev/null 2>&1; then
  if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] || hyprctl monitors >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
  fi
fi
