# // █▀▀ █▀█ █▀▀ █░█ █▀
# // █▀░ █▄█ █▄▄ █▄█ ▄█

$WORKFLOW_ICON=󰽏
$WORKFLOW_DESCRIPTION = Focused workspace // Disables animations and blur with focus-mode geometry overrides

decoration {
    shadow {
        enabled = 0
    }
    blur {
        enabled = 0
        xray = 1
    }
    rounding = 4
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
}

general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
}

animations:enabled = 0

layerrule = animation none, match:namespace waybar
layerrule = animation none, match:namespace notifications
layerrule = animation none, match:namespace awww-daemon
layerrule = animation none, match:namespace rofi

windowrule = opaque 1, match:class (.*)
