-- Generated native Hyprland Lua. Do not edit manually.
local runtime = require("runtime")
local vars = require("vars")

vars.set("WORKFLOW_ICON", "")
vars.set("WORKFLOW_DESCRIPTION", "Emphasis on performance and disabling compositors expensive features")
runtime.config("decoration.shadow.enabled", 0)
runtime.config("decoration.blur.enabled", 0)
runtime.config("decoration.blur.xray", 1)
runtime.config("decoration.rounding", 0)
runtime.config("decoration.active_opacity", 1)
runtime.config("decoration.inactive_opacity", 1)
runtime.config("decoration.fullscreen_opacity", 1)
runtime.config("general.gaps_in", 0)
runtime.config("general.gaps_out", 0)
runtime.config("general.border_size", 1)
runtime.config("animations.enabled", 0)
hl.layer_rule({["name"] = "lua:workflow:gaming:31", ["match"] = {["namespace"] = "waybar"}, ["animation"] = "none"})
hl.layer_rule({["name"] = "lua:workflow:gaming:32", ["match"] = {["namespace"] = "notifications"}, ["animation"] = "none"})
hl.layer_rule({["name"] = "lua:workflow:gaming:33", ["match"] = {["namespace"] = "awww-daemon"}, ["animation"] = "none"})
hl.layer_rule({["name"] = "lua:workflow:gaming:34", ["match"] = {["namespace"] = "rofi"}, ["animation"] = "none"})
hl.window_rule({["name"] = "lua:workflow:gaming:36", ["match"] = {["class"] = "(.*)"}, ["opaque"] = true})
