background = "#1E1E2E"
foreground = "#CDD6F4"
cursor-color = "#F5E0DC"
cursor-text = "#1E1E2E"
selection-foreground = "#1E1E2E"
selection-background = "#F5E0DC"

colors = [
  "#43465A",
  "#F38BA8",
  "#A6E3A1",
  "#F9E2AF",
  "#87B0F9",
  "#F5C2E7",
  "#94E2D5",
  "#CDD6F4",
  "#43465A",
  "#F38BA8",
  "#A6E3A1",
  "#F9E2AF",
  "#87B0F9",
  "#F5C2E7",
  "#94E2D5",
  "#A1A8C9",
]
