$HOME/.config/rofi/theme.rasi
* {
    background:            #11111be6;
    background-alpha:    #11111b59;
    foreground:            #cdd6f4ff;
    border:            #cba6f7ff;
    accent:            #CBA6F7ff;
    selected-background:          #313244ff;
    selected-foreground:          #89b4faff;
    separator:           #80808080;
    urgent:              #f38ba8ff;
    active:              #a6e3a1ff;
}
