background = "#130808"
foreground = "#c4c1c1"
cursor = "#c4c1c1"

colors = [
  "#1e0f0f",
  "#d32d38",
  "#90b486",
  "#d4a030",
  "#8b6aad",
  "#c74b8a",
  "#5ba8a0",
  "#968c8c",
  "#6b5757",
  "#e04550",
  "#a4c89a",
  "#e2b44a",
  "#a482c4",
  "#d968a0",
  "#74bfb7",
  "#c4c1c1",
]
