$HOME/.config/rofi/theme.rasi
* {
    background:            #1e0f0fe6;
    background-alpha:    #1e0f0f59;
    foreground:            #c4c1c1ff;
    border:            #462f4aff;
    accent:            #d32d38ff;
    selected-background:          #d32d38ff;
    selected-foreground:          #130808ff;
    separator:           #80808080;
    urgent:              #e04550ff;
    active:              #90b486ff;
}
