background = "#0c1021"
foreground = "#fdfff1"
cursor-color = "#f25e01"
cursor-text = "#FFFFFF"
selection-foreground = "#0c1021"
selection-background = "#FFFFFF"

colors = [
  "#0a0d1a",
  "#e04a5f",
  "#55ba30",
  "#b3f63a",
  "#6b8ab8",
  "#ff0cac",
  "#97c7e9",
  "#d8d9c8",
  "#505257",
  "#f25e01",
  "#b3f63a",
  "#f8e9c7",
  "#97c7e9",
  "#ff0cac",
  "#f5c6b0",
  "#fdfff1",
]
