$HOME/.config/rofi/theme.rasi
* {
    background:            #28432FB3;
    background-alpha:      #28432F59;
    foreground:            #578F8FE6;
    border:                #11b811E6;
    accent:                #153550E6;
    selected-background:   #AAF0AA80;
    selected-foreground:   #AAF0F0E6;
    separator:             #80808080;
    urgent:                #153550E6;
    active:                #578F8FE6;
}
