$HOME/.config/rofi/theme.rasi
* {
    background:            #282828e6;
    foreground:            #ebdbb2ff;
    border:            #d79921ff;
    accent:            #fabd2fff;
    selected-background:          #98971aff;
    selected-foreground:          #282828ff;
    separator:           #80808080;
    urgent:              #fb4934ff;
    active:              #b8bb26ff;
    separatorcolor:     #504945ff;
    border-color:       #665c54ff;
    font: "Monocraft Nerd Font 10";
}
