background = "#323d43"
foreground = "#d8caac"
cursor-color = "#d8caac"
cursor-text = "#323d43"
selection-foreground = "#d8caac"
selection-background = "#505a60"

colors = [
  "#3c474d",
  "#e68183",
  "#a7c080",
  "#d9bb80",
  "#83b6af",
  "#d39bb6",
  "#87c095",
  "#868d80",
  "#868d80",
  "#e68183",
  "#a7c080",
  "#d9bb80",
  "#83b6af",
  "#d39bb6",
  "#87c095",
  "#868d80",
]
