$HOME/.config/rofi/theme.rasi
* {
    background:            #2f3330;
    foreground:            #d8dee9;
    border:                #3b4252;
    accent:                #e5c07b;
    selected-background:   #3b4252;
    selected-foreground:   #eceff4;
    separator:           #80808080;
    urgent:              #cc6666ff;
    active:              #b5bd68ff;
    separatorcolor:     transparent;
    border-color:       transparent;
}
