$HOME/.config/rofi/theme.rasi
* {

    background:            #2f3330;
    background-alpha:    #2f333059;
    foreground:            #d8dee9;
    border:                #a6a6a680;
    active:                #83b6af;
    accent:                #859289;
    selected-foreground:   #eceff4;
    separator:             #80808080;
    urgent:                #e67e80;
    selected-background:   #5d6b66;
}
