background = "#2C2525"
foreground = "#F8F8F2"
cursor-color = "#F8F8F2"
cursor-text = "#2d2a2e"
selection-foreground = "#2C2525"
selection-background = "#F8F8F2"

colors = [
  "#272822",
  "#F92672",
  "#A6E3A1",
  "#F9E2AF",
  "#F38D70",
  "#F5C2E7",
  "#94E2D5",
  "#F8F8F2",
  "#807d74",
  "#F92672",
  "#A6E3A1",
  "#F9E2AF",
  "#F38D70",
  "#F5C2E7",
  "#94E2D5",
  "#F8F8F2",
]
