$HOME/.config/alacritty/theme.toml

[colors.primary]
background = "#0b0d11"
foreground = "#f0b7ca"

[colors.cursor]
text = "#0b0d11"
cursor = "#f23888"

[colors.selection]
text = "#0b0d11"
background = "#f23888"

[colors.normal]
black = "#0b0d11"
red = "#f23888"
green = "#5aa15d"
yellow = "#d7be96"
blue = "#67dd82"
magenta = "#f0b7ca"
cyan = "#6f9485"
white = "#f0b7ca"

[colors.bright]
black = "#678270"
red = "#ff6aa7"
green = "#86bf86"
yellow = "#e6d3b4"
blue = "#8bf0a1"
magenta = "#ffd0dc"
cyan = "#8bb0a4"
white = "#fff1f6"
