$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-pink-dark
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = aether
$NVIM_VARIANT = sakura-mochi
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = true
$CURSOR_THEME = Emo
$CURSOR_SIZE = 30
$FONT = M+1Code Nerd Font
$BAR_FONT = M+1Code Nerd Font
$MENU_FONT = M+1Code Nerd Font
$MONOSPACE_FONT = M+1Code Nerd Font
$TERMINAL_FONT = M+1Code Nerd Font
$NOTIFICATION_FONT = M+1Code Nerd Font Mono

general {
    col.active_border = rgba(f23888ee)
    col.inactive_border = rgba(5aa15d99)
    border_size = 2
    gaps_in = 6
    gaps_out = 12
}

group {
    col.border_active = rgba(f23888ee)
    col.border_inactive = rgba(5aa15d99)
}

decoration {
  active_opacity = 0.97
  inactive_opacity = 0.95
    rounding = 4

    blur {
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.03
        contrast = 0.87
        vibrancy = 0.03
        vibrancy_darkness = 0.7
        brightness = 0.42
        popups_ignorealpha = 0.5
        input_methods_ignorealpha = 0.5
    }

    shadow {
        enabled = true
        range = 16
        render_power = 3
        color = rgba(0b0d118c)
        color_inactive = rgba(0b0d118c)
        offset = 2 2
    }
}
