$HOME/.config/kitty/theme.conf

background #0b0d11
foreground #f0b7ca
cursor #f23888
cursor_text_color #0b0d11
selection_foreground #0b0d11
selection_background #f23888

color0 #0b0d11
color1 #f23888
color2 #5aa15d
color3 #d7be96
color4 #67dd82
color5 #f0b7ca
color6 #6f9485
color7 #f0b7ca
color8 #678270
color9 #ff6aa7
color10 #86bf86
color11 #e6d3b4
color12 #8bf0a1
color13 #ffd0dc
color14 #8bb0a4
color15 #fff1f6
