background = "#0b0d11"
foreground = "#f0b7ca"
cursor-color = "#f23888"
cursor-text = "#0b0d11"
selection-foreground = "#0b0d11"
selection-background = "#f23888"
kvantum-shell = "pill"

colors = [
  "#0b0d11",
  "#f23888",
  "#5aa15d",
  "#d7be96",
  "#67dd82",
  "#f0b7ca",
  "#6f9485",
  "#f0b7ca",
  "#678270",
  "#ff6aa7",
  "#86bf86",
  "#e6d3b4",
  "#8bf0a1",
  "#ffd0dc",
  "#8bb0a4",
  "#fff1f6",
]
