background = "#ffffff"
foreground = "#262626"
cursor = "#6fd2fc"

colors = [
  "#000000",
  "#f72729",
  "#32895c",
  "#f96f1c",
  "#125ccf",
  "#9f00bc",
  "#32c2c0",
  "#b2b2b2",
  "#545753",
  "#fb0416",
  "#2cc631",
  "#fcd627",
  "#156ffe",
  "#e800b0",
  "#39d5ce",
  "#ededec",
]
