$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Fluent-grey
$COLOR_SCHEME = prefer-light
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = Adwaita
$CURSOR_SIZE = 30
$FONT = GeistMono Nerd Font
$BAR_FONT = GeistMono Nerd Font
$MENU_FONT = GeistMono Nerd Font
$MONOSPACE_FONT = GeistMono Nerd Font
$TERMINAL_FONT = GeistMono Nerd Font
$NOTIFICATION_FONT = GeistMono Nerd Font Mono

general {
    col.active_border = rgb(2B2C2B)
    col.inactive_border = rgb(B3B4B4)
    border_size = 2
    gaps_in = 2
    gaps_out = 4
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgb(2B2C2B)
    col.border_inactive = rgb(B3B4B4)
    col.border_locked_active = rgb(2B2C2B)
    col.border_locked_inactive = rgb(B3B4B4)
}

decoration {
    rounding = 6
    shadow {
        enabled = false
        range = 15
        render_power = 5
        offset = 0 0
    }

    blur {
        enabled = true
        size = 2
        passes = 4
        contrast = 1.1
        brightness = 1.1
        vibrancy = 0.2
        vibrancy_darkness = 0.2
        noise = 0.03
        ignore_opacity = true
        new_optimizations = on
    }
    active_opacity = 0.98
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0
}
