$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-blue-light
$COLOR_SCHEME = prefer-light
$NVIM_SCHEME = bamboo
$NVIM_VARIANT = light
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = capitaine-cursors-light
$CURSOR_SIZE = 30
$FONT = Cousine Nerd Font
$BAR_FONT = Cousine Nerd Font
$MENU_FONT = Cousine Nerd Font
$MONOSPACE_FONT = Cousine Nerd Font
$TERMINAL_FONT = Cousine Nerd Font
$NOTIFICATION_FONT = Cousine Nerd Font Mono

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(50a3b5ee) rgba(0e8fb5ee) 45deg
    col.inactive_border = rgba(b8a796cc) rgba(4a5a65cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(50a3b5ee) rgba(0e8fb5ee) 45deg
    col.border_inactive = rgba(b8a796cc) rgba(4a5a65cc) 45deg
}

decoration {
    rounding = 4
    blur {
        enabled = yes
        size = 4
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    shadow {
        enabled = false
    }
}
