$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta
$ICON_THEME = Tela-red-dark
$CURSOR_THEME = Skyrim-by-ru5tyshark-cursors
$CURSOR_SIZE = 40
# $CURSOR_THEME = taiga-cursor
# $CURSOR_SIZE = 30
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = ashen
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$FONT = IosevkaTerm Nerd Font
$BAR_FONT = IosevkaTerm Nerd Font
$MENU_FONT = IosevkaTerm Nerd Font
$MONOSPACE_FONT = IosevkaTerm Nerd Font
$TERMINAL_FONT = IosevkaTerm Nerd Font
$NOTIFICATION_FONT = IosevkaTerm Nerd Font Mono

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(B41211ff)
    col.inactive_border = rgba(3d3935ff)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(B41211ff)
    col.border_inactive = rgba(3d3935cc) 
    col.border_locked_active = rgba(FFFFFFff)
    col.border_locked_inactive = rgba(FFFFFFcc)
}

decoration {
    rounding = 3

    blur {
        enabled = yes
        size = 4
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    shadow {
        enabled = false
    }
}
