hl.window_rule({["name"] = "haruna-idle-inhibit", ["match"] = {["class"] = "^(.*haruna.*)$"}, ["idle_inhibit"] = "fullscreen"})
hl.window_rule({["name"] = "firefox-chromium-idle-inhibit", ["match"] = {["class"] = "^(.*firefox.*)$|^(.*chromium.*)$"}, ["idle_inhibit"] = "fullscreen"})
hl.window_rule({["name"] = "tag-picture-in-picture", ["match"] = {["title"] = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"}, ["tag"] = "+picture-in-picture"})
hl.window_rule({["name"] = "picture-in-picture-float", ["match"] = {["tag"] = "picture-in-picture"}, ["float"] = true})
hl.window_rule({["name"] = "picture-in-picture-keep-aspect", ["match"] = {["tag"] = "picture-in-picture"}, ["keep_aspect_ratio"] = true})
hl.window_rule({["name"] = "picture-in-picture-position", ["match"] = {["tag"] = "picture-in-picture"}, ["move"] = "73% 72%"})
hl.window_rule({["name"] = "picture-in-picture-size", ["match"] = {["tag"] = "picture-in-picture"}, ["size"] = "25% 25%"})
hl.window_rule({["name"] = "picture-in-picture-pin", ["match"] = {["tag"] = "picture-in-picture"}, ["pin"] = true})
hl.window_rule({["name"] = "dropdown-terminal-float", ["match"] = {["class"] = "^(dropdown-terminal)$"}, ["float"] = true})
hl.window_rule({["name"] = "dropdown-terminal-opacity", ["match"] = {["class"] = "^(dropdown-terminal)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "haruna-main-window-fullscreen", ["match"] = {["class"] = "^(org\\.kde\\.haruna)$", ["initial_title"] = "^Haruna$"}, ["fullscreen"] = true})
hl.window_rule({["name"] = "haruna-float", ["match"] = {["class"] = "^(org\\.kde\\.haruna)$"}, ["float"] = true})
hl.window_rule({["name"] = "firefox-opacity", ["match"] = {["class"] = "^(firefox)$"}, ["opacity"] = "0.90 override 0.90 override 1"})
hl.window_rule({["name"] = "brave-browser-opacity", ["match"] = {["class"] = "^(brave-browser)$"}, ["opacity"] = "0.90 override 0.90 override 1"})
hl.window_rule({["name"] = "kitty-opacity", ["match"] = {["class"] = "^(kitty)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "alacritty-opacity", ["match"] = {["class"] = "^(Alacritty)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "dolphin-opacity", ["match"] = {["class"] = "^(org\\.kde\\.dolphin)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "ark-opacity", ["match"] = {["class"] = "^(org\\.kde\\.ark)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "qbittorrent-opacity", ["match"] = {["class"] = "^(org\\.qbittorrent\\.qBittorrent)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "nwg-look-opacity", ["match"] = {["class"] = "^(nwg-look)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "nwg-displays-opacity", ["match"] = {["class"] = "^(nwg-displays)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "kvantummanager-opacity", ["match"] = {["class"] = "^(kvantummanager)$"}, ["opacity"] = "0.80 override 0.80 override 1"})
hl.window_rule({["name"] = "pavucontrol-opacity", ["match"] = {["class"] = "^(.*pavucontrol.*)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "blueman-manager-opacity", ["match"] = {["class"] = "^(blueman-manager)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "nm-applet-opacity", ["match"] = {["class"] = "^(nm-applet)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "nm-connection-editor-opacity", ["match"] = {["class"] = "^(nm-connection-editor)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "polkit-kde-agent-opacity", ["match"] = {["class"] = "^(org\\.kde\\.polkit-kde-authentication-agent-1)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "polkit-gnome-agent-opacity", ["match"] = {["class"] = "^(polkit-gnome-authentication-agent-1)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "portal-gtk-opacity", ["match"] = {["class"] = "^(org\\.freedesktop\\.impl\\.portal\\.desktop\\.gtk)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "portal-hyprland-opacity", ["match"] = {["class"] = "^(org\\.freedesktop\\.impl\\.portal\\.desktop\\.hyprland)$"}, ["opacity"] = "0.80 override 0.70 override 1"})
hl.window_rule({["name"] = "gimp-main-window-fullscreen", ["match"] = {["class"] = "^(gimp)$", ["initial_title"] = "^GNU Image Manipulation Program$"}, ["fullscreen"] = true})
hl.window_rule({["name"] = "flatseal-opacity", ["match"] = {["class"] = "^(com\\.github\\.tchx84\\.Flatseal)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "pupgui2-opacity", ["match"] = {["class"] = "^(net\\.davidotek\\.pupgui2)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "yad-opacity", ["match"] = {["class"] = "^(yad)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "signal-opacity", ["match"] = {["class"] = "^(signal)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "zathura-opacity", ["match"] = {["class"] = "^(org\\.pwmt\\.zathura)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "bitwarden-opacity", ["match"] = {["class"] = "^([Bb]itwarden)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "chromium-opacity", ["match"] = {["class"] = "^(chromium)$"}, ["opacity"] = "0.90 0.90"})
hl.window_rule({["name"] = "webcord-opacity", ["match"] = {["class"] = "^(io\\.github\\.spacingbat3\\.webcord)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "skanlite-opacity", ["match"] = {["class"] = "^(org\\.kde\\.skanlite)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "curtail-opacity", ["match"] = {["class"] = "^(com\\.github\\.huluti\\.Curtail)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "pdfarranger-opacity", ["match"] = {["class"] = "^(com\\.github\\.jeromerobert\\.pdfarranger)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "swappy-opacity", ["match"] = {["class"] = "^(swappy)$"}, ["opacity"] = "0.80 0.80"})
hl.window_rule({["name"] = "gwenview-suppress-fullscreen", ["match"] = {["class"] = "^(org\\.kde\\.gwenview)$"}, ["suppress_event"] = "fullscreen"})
hl.window_rule({["name"] = "gwenview-fullscreen", ["match"] = {["class"] = "^(org\\.kde\\.gwenview)$", ["modal"] = false}, ["fullscreen"] = true})
hl.window_rule({["name"] = "libreoffice-own-workspace", ["match"] = {["class"] = "^([Ll]ibreoffice(-writer|-calc|-impress|-draw|-base|-math|-startcenter)?)$", ["modal"] = false}, ["workspace"] = "empty"})
hl.window_rule({["name"] = "qalculate-gtk-float", ["match"] = {["class"] = "^(qalculate-gtk)$"}, ["float"] = true})
hl.window_rule({["name"] = "blueman-manager-float", ["match"] = {["class"] = "^(blueman-manager)$"}, ["float"] = true})
hl.window_rule({["name"] = "clapper-float", ["match"] = {["class"] = "^(com\\.github\\.rafostar\\.Clapper)$"}, ["float"] = true})
hl.window_rule({["name"] = "warp-float", ["match"] = {["class"] = "^(app\\.drey\\.Warp)$"}, ["float"] = true})
hl.window_rule({["name"] = "pupgui2-float", ["match"] = {["class"] = "^(net\\.davidotek\\.pupgui2)$"}, ["float"] = true})
hl.window_rule({["name"] = "yad-float", ["match"] = {["class"] = "^(yad)$"}, ["float"] = true})
hl.window_rule({["name"] = "planify-float", ["match"] = {["class"] = "^(io\\.github\\.alainm23\\.planify)$"}, ["float"] = true})
hl.window_rule({["name"] = "upscaler-float", ["match"] = {["class"] = "^(io\\.gitlab\\.theevilskeleton\\.Upscaler)$"}, ["float"] = true})
hl.window_rule({["name"] = "videodownloader-float", ["match"] = {["class"] = "^(com\\.github\\.unrud\\.VideoDownloader)$"}, ["float"] = true})
hl.window_rule({["name"] = "impression-float", ["match"] = {["class"] = "^(io\\.gitlab\\.adhami3310\\.Impression)$"}, ["float"] = true})
hl.window_rule({["name"] = "partitionmanager-float", ["match"] = {["class"] = "^(org\\.kde\\.partitionmanager)$"}, ["float"] = true})
hl.window_rule({["name"] = "qbittorrent-float", ["match"] = {["class"] = "^(org\\.qbittorrent\\.qBittorrent)$"}, ["float"] = true})
hl.window_rule({["name"] = "qbittorrent-main-window-tile", ["match"] = {["class"] = "^(org\\.qbittorrent\\.qBittorrent)$", ["initial_title"] = "^qBittorrent v[0-9]"}, ["float"] = false})
hl.window_rule({["name"] = "qbittorrent-main-window-retitled-tile", ["match"] = {["class"] = "^(org\\.qbittorrent\\.qBittorrent)$", ["title"] = "^qBittorrent v[0-9]"}, ["float"] = false})
hl.window_rule({["name"] = "transmission-main-window-tile", ["match"] = {["class"] = "^(com\\.transmissionbt\\.transmission|transmission-gtk).*$", ["title"] = "^Transmission$"}, ["float"] = false})
hl.window_rule({["name"] = "transmission-preferences-tile", ["match"] = {["class"] = "^(com\\.transmissionbt\\.transmission|transmission-gtk).*$", ["title"] = "^Transmission Preferences$"}, ["float"] = false})
hl.window_rule({["name"] = "xdg-desktop-portal-gtk-float", ["match"] = {["class"] = "^(xdg-desktop-portal-gtk)$"}, ["float"] = true})
hl.window_rule({["name"] = "xdg-desktop-portal-gtk-center", ["match"] = {["class"] = "^(xdg-desktop-portal-gtk)$"}, ["center"] = true})
hl.window_rule({["name"] = "hyprland-share-picker-float", ["match"] = {["class"] = "^(hyprland-share-picker)$"}, ["float"] = true})
hl.window_rule({["name"] = "hyprland-share-picker-center", ["match"] = {["class"] = "^(hyprland-share-picker)$"}, ["center"] = true})
hl.window_rule({["name"] = "bitwarden-float", ["match"] = {["class"] = "^([Bb]itwarden)$"}, ["float"] = true})
hl.window_rule({["name"] = "skanlite-float", ["match"] = {["class"] = "^(org\\.kde\\.skanlite)$"}, ["float"] = true})
hl.window_rule({["name"] = "swappy-float", ["match"] = {["class"] = "^(swappy)$"}, ["float"] = true})
hl.window_rule({["name"] = "swappy-center", ["match"] = {["class"] = "^(swappy)$"}, ["center"] = true})
hl.window_rule({["name"] = "localsend-float", ["match"] = {["class"] = "^(localsend)$"}, ["float"] = true})
hl.window_rule({["name"] = "localsend-center", ["match"] = {["class"] = "^(localsend)$"}, ["center"] = true})
hl.window_rule({["name"] = "nwg-displays-float", ["match"] = {["class"] = "^(nwg-displays)$"}, ["float"] = true})
hl.window_rule({["name"] = "keditfiletype-float", ["match"] = {["class"] = "^(org\\.kde\\.keditfiletype)$"}, ["float"] = true})
hl.window_rule({["name"] = "jetbrains-popups-no-initial-focus", ["match"] = {["class"] = "^(.*jetbrains.*)$", ["title"] = "^(win[0-9]+)$"}, ["no_initial_focus"] = true})
hl.layer_rule({["name"] = "rofi-blur", ["match"] = {["namespace"] = "rofi"}, ["blur"] = true})
hl.layer_rule({["name"] = "rofi-ignore-alpha", ["match"] = {["namespace"] = "rofi"}, ["ignore_alpha"] = 0})
hl.layer_rule({["name"] = "notifications-blur", ["match"] = {["namespace"] = "notifications"}, ["blur"] = true})
hl.layer_rule({["name"] = "notifications-ignore-alpha", ["match"] = {["namespace"] = "notifications"}, ["ignore_alpha"] = 0})
hl.layer_rule({["name"] = "logout-dialog-blur", ["match"] = {["namespace"] = "logout_dialog"}, ["blur"] = true})
hl.window_rule({["name"] = "tui-apps-float", ["match"] = {["class"] = "^(org\\.tui\\..*|org\\.font\\..*|lazygit|lazydocker)$"}, ["float"] = true})
hl.window_rule({["name"] = "tui-apps-center", ["match"] = {["class"] = "^(org\\.tui\\..*|org\\.font\\..*|lazygit|lazydocker)$"}, ["center"] = true})
