# style name or JSON path (default "auto")
style: "/home/rifle/.cache/hypr/render/glow/style.json"
# mouse support (TUI-mode only)
mouse: false
# use pager to display markdown
pager: false
# word-wrap at width
width: 0
# show all files, including hidden and ignored.
all: false
