$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Fluent-yellow-dark
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = pywal
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = Emo
$CURSOR_SIZE = 30

general {
    col.active_border = rgba(c87d2af5) rgba(fffaf0f5) 45deg
    col.inactive_border = rgba(6b5650f5)
    border_size = 3
    gaps_in = 6
    gaps_out = 12
}

group {
    col.border_active = rgba(c87d2af5) rgba(fffaf0f5) 45deg
    col.border_inactive = rgba(6b5650f5)
}

decoration {
    rounding = 6
    rounding_power = 2
    blur {
        enabled = true
        size = 5
        passes = 2
    }
    shadow {
        enabled = true
        range = 14
        render_power = 3
        color = rgba(33282db5)
        color_inactive = rgba(292025d8)
    }
}
