background = "#272727"
foreground = "#ebdbb2"
cursor-color = "#928374"
cursor-text = "#272727"
selection-foreground = "#655b53"
selection-background = "#ebdbb2"

colors = [
  "#272727",
  "#cc231c",
  "#989719",
  "#d79920",
  "#448488",
  "#b16185",
  "#689d69",
  "#a89983",
  "#928373",
  "#fb4833",
  "#b8ba25",
  "#fabc2e",
  "#83a597",
  "#d3859a",
  "#8ec07b",
  "#ebdbb2",
]
