#!/usr/bin/env bash
# Theme metadata writer for Hyprland

[[ "${HYPR_SHELL_INIT}" -ne 1 ]] && eval "$(hyprshell init)"

# Don't run during startup
[[ "${PYWAL_STARTUP:-0}" -eq 1 ]] && exit 0

cacheDir="${cacheDir:-$XDG_CACHE_HOME}"
confDir="${confDir:-$XDG_CONFIG_HOME}"
HYPR_THEME="${HYPR_THEME:-}"
HYPR_THEME_DIR="${HYPR_THEME_DIR:-$confDir/hypr/themes/$HYPR_THEME}"
enableWallDcol="${enableWallDcol:-1}"

# Get theme settings
if [ ! -f "${HYPR_THEME_DIR}/hypr.theme" ]; then
  echo "[wal.hypr] Warning: hypr.theme not found at ${HYPR_THEME_DIR}"
fi

eval "$(
  hyq "${HYPR_THEME_DIR}/hypr.theme" \
    --export env \
    -Q "\$GTK_THEME[string]" \
    -Q "\$COLOR_SCHEME[string]" \
    -Q "\$ICON_THEME[string]" \
    -Q "\$CURSOR_THEME[string]" \
    -Q "\$CURSOR_SIZE[int]" \
    -Q "\$FONT[string]" \
    -Q "\$FONT_SIZE[int]" \
    -Q "\$DOCUMENT_FONT[string]" \
    -Q "\$DOCUMENT_FONT_SIZE[int]" \
    -Q "\$MONOSPACE_FONT[string]" \
    -Q "\$MONOSPACE_FONT_SIZE[int]" \
    -Q "\$CODE_THEME[string]"
)"

# Pywal16 mode mapping
case "${enableWallDcol}" in
  0) mode_name="theme" ;;
  1) mode_name="auto" ;;
  2) mode_name="dark" ;;
  3) mode_name="light" ;;
  *) mode_name="auto" ;;
esac

# Write metadata
mkdir -p "${confDir}/hypr/themes"
cat <<WAL >"${confDir}/hypr/themes/wal.conf"
# Auto-generated by wal.hypr.sh - Read-only
# Theme: ${HYPR_THEME}
# Configuration: "${HYPR_THEME_DIR}/hypr.theme"
# Mode: ${mode_name}

\$HYPR_THEME=${HYPR_THEME}
\$GTK_THEME=${__GTK_THEME:-\$GTK_THEME}
\$COLOR_SCHEME=${__COLOR_SCHEME:-\$COLOR_SCHEME}
\$ICON_THEME=${__ICON_THEME}

\$CURSOR_THEME=${__CURSOR_THEME:-\$CURSOR_THEME}
\$CURSOR_SIZE=${__CURSOR_SIZE:-\$CURSOR_SIZE}

\$FONT=${__FONT:-\$FONT}
\$FONT_SIZE=${__FONT_SIZE:-\$FONT_SIZE}
\$DOCUMENT_FONT=${__DOCUMENT_FONT:-\$DOCUMENT_FONT}
\$DOCUMENT_FONT_SIZE=${__DOCUMENT_FONT_SIZE:-\$DOCUMENT_FONT_SIZE}
\$MONOSPACE_FONT=${__MONOSPACE_FONT:-\$MONOSPACE_FONT}
\$MONOSPACE_FONT_SIZE=${__MONOSPACE_FONT_SIZE:-\$MONOSPACE_FONT_SIZE}

\$CODE_THEME=${__CODE_THEME:-\$CODE_THEME}
\$SDDM_THEME=${__SDDM_THEME:-\$CODE_THEME}

# // ----------------------------
# README:
# Values above are derived and sanitized from the theme.conf file,
# This is to ensure themes won't have any 'exec' or 'source'
# commands that could potentially harm the system
# or undesired behavior.
#
# You can still add your own custom 'exec' or 'source' commands
# by adding it as variable, examples (you can name the variable anything):
# Note that you should indicate it in your README.md
#
#
# -- ⌨️ theme.conf --
# \$RUN_CMD="some_command"
# \$SOURCE_FILE="/some/files"
#
#
# -- ⌨️ userprefs.conf --
# exec = \${RUN_CMD}"
# source = \${SOURCE_FILE}
# exec = hyprshell wal code \$CODE_THEME # Setting the code theme

# // ----------------------------
WAL

if grep -q "#//---Wallpaper mode enabled---\|#//---Pywal16 mode enabled---" "${confDir}/hypr/themes/wal.conf"; then
  # Remove lines below the detected line
  sed -i '/#\/\/---Wallpaper mode enabled---/,$d; /#\/\/---Pywal16 mode enabled---/,$d' "${confDir}/hypr/themes/wal.conf"
fi

if [[ "${enableWallDcol}" -gt 0 ]]; then
  cat <<ON_WAL >>"${confDir}/hypr/themes/wal.conf"

#//---Wallpaper mode enabled---
# Overriding values above

\$GTK_THEME = Pywal16-Gtk
\$COLOR_SCHEME = ${COLOR_SCHEME}

ON_WAL

  cat $HOME/.cache/wal/colors-hyprland.conf >>"${confDir}/hypr/themes/wal.conf" 2>/dev/null || true
fi
