#!/bin/bash
# Convert pywal colors (0-1.0 range) to hyprlock format (0-255 integers)

PYWAL_COLORS="${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.json"
HYPRLOCK_COLORS="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/colors.conf"

# Check if pywal colors exist
if [ ! -f "$PYWAL_COLORS" ]; then
  echo "Error: Pywal colors not found at $PYWAL_COLORS"
  exit 1
fi

# Create hyprlock colors directory if it doesn't exist
mkdir -p "$(dirname "$HYPRLOCK_COLORS")"

# Convert colors using Python
PYWAL_COLORS="$PYWAL_COLORS" python3 - >"$HYPRLOCK_COLORS" <<'PYTHON_EOF'
import json
import os

colors_file = os.environ['PYWAL_COLORS']
with open(colors_file, 'r') as f:
    colors = json.load(f)

def hex_to_rgb(hex_color):
    """Convert hex color to RGB integers (0-255)"""
    hex_color = hex_color.lstrip('#')
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

print("# Autogenerated hyprlock colors from pywal16")
print("# RGB values in 0-255 integer range\n")

# Standard colors - individual RGB components
for i in range(16):
    key = f"color{i}"
    r, g, b = hex_to_rgb(colors['colors'][key])
    print(f"$c{i}.r = {r}")
    print(f"$c{i}.g = {g}")
    print(f"$c{i}.b = {b}")
    print(f"$color{i} = rgb({r}, {g}, {b})")
    print()

# Special colors - individual RGB components
for key in ['background', 'foreground', 'cursor']:
    if key in colors['special']:
        r, g, b = hex_to_rgb(colors['special'][key])
        short_key = 'bg' if key == 'background' else 'fg' if key == 'foreground' else 'cx'
        print(f"${short_key}.r = {r}")
        print(f"${short_key}.g = {g}")
        print(f"${short_key}.b = {b}")
        print(f"${key} = rgb({r}, {g}, {b})")
        print()

print("# RGBA versions with alpha channel (40% opacity)")

# Alpha versions
for i in range(16):
    key = f"color{i}"
    r, g, b = hex_to_rgb(colors['colors'][key])
    print(f"$color{i}_alpha = rgba({r}, {g}, {b}, 0.4)")

print()

# Special colors with alpha
for key in ['background', 'foreground']:
    if key in colors['special']:
        r, g, b = hex_to_rgb(colors['special'][key])
        print(f"${key}_alpha = rgba({r}, {g}, {b}, 0.4)")

PYTHON_EOF

echo "Hyprlock colors generated at $HYPRLOCK_COLORS"
