#!/usr/bin/env bash
# Pywal16 overrides for Hyprland
#
# Writes wal.conf with:
#   - $HYPR_THEME (always, needed by finale.conf)
#   - In wallpaper mode: $GTK_THEME=Pywal16-Gtk, $COLOR_SCHEME, and pywal16 colors
#
# Theme metadata ($GTK_THEME, $ICON_THEME, fonts, cursors, etc.) lives in
# theme.conf, generated by sanitize_hypr_theme() during theme switches.

set -euo pipefail

# shellcheck source=/dev/null
source "$(command -v hyprshell)" || exit 1

# Don't run during startup
[[ "${PYWAL_STARTUP:-0}" -eq 1 ]] && exit 0

HYPR_THEME="${HYPR_THEME:-}"
selected_color_mode="${selected_color_mode:-1}"

resolve_wallpaper_color_scheme() {
  local state_home="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}"
  local variant="${resolved_color_variant:-}"

  if [[ "${variant}" != "dark" && "${variant}" != "light" ]]; then
    case "${selected_color_mode}" in
      2) variant="dark" ;;
      3) variant="light" ;;
      1)
        if [[ -r "${state_home}/color_variant" ]]; then
          variant="$(<"${state_home}/color_variant")"
        fi
        if [[ "${variant}" != "dark" && "${variant}" != "light" ]] && [[ -r "${state_home}/staterc" ]]; then
          variant="$(awk -F= '/^BACKGROUND_MODE=/{gsub(/"/,"",$2);print $2; exit}' "${state_home}/staterc" 2>/dev/null)"
        fi
        ;;
    esac
  fi

  [[ "${variant}" == "light" ]] && printf '%s\n' "prefer-light" || printf '%s\n' "prefer-dark"
}

case "${selected_color_mode}" in
  0) mode_name="theme" ;;
  1) mode_name="auto" ;;
  2) mode_name="dark" ;;
  3) mode_name="light" ;;
  *) mode_name="auto" ;;
esac

mkdir -p "${HYPR_CONFIG_HOME}/themes"

if [[ "${selected_color_mode}" -gt 0 ]]; then
  # Wallpaper mode: override GTK theme to pywal-generated one and append colors
  cat <<WAL >"${HYPR_CONFIG_HOME}/themes/wal.conf"
# Auto-generated by wal.hypr.sh — pywal16 overrides only
# Theme: ${HYPR_THEME} | Mode: ${mode_name}

\$HYPR_THEME=${HYPR_THEME}

#//---Wallpaper mode enabled---
\$GTK_THEME = Pywal16-Gtk
\$COLOR_SCHEME = $(resolve_wallpaper_color_scheme)

WAL
  cat "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors-hyprland.conf" >>"${HYPR_CONFIG_HOME}/themes/wal.conf" || exit 1
else
  # Theme mode: only set $HYPR_THEME; colors and metadata come from theme.conf
  cat <<WAL >"${HYPR_CONFIG_HOME}/themes/wal.conf"
# Auto-generated by wal.hypr.sh — theme mode (no pywal16 overrides)
# Theme: ${HYPR_THEME}

\$HYPR_THEME=${HYPR_THEME}
WAL
fi
