QT_QPA_PLATFORMTHEME=kde
QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-wayland;xcb}"

MOZ_ENABLE_WAYLAND="${MOZ_ENABLE_WAYLAND:-1}"
GDK_SCALE="${GDK_SCALE:-1}"
ELECTRON_OZONE_PLATFORM_HINT="${ELECTRON_OZONE_PLATFORM_HINT:-auto}"

# Let Hyprland select hyprland.lua; discard stale values inherited from shells.
unset HYPRLAND_CONFIG
# UWSM owns readiness and the activation environment.
HYPRLAND_NO_SD_NOTIFY=1
HYPRLAND_NO_SD_VARS=1

export ELECTRON_OZONE_PLATFORM_HINT GDK_SCALE MOZ_ENABLE_WAYLAND \
  QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME \
  HYPRLAND_NO_SD_NOTIFY HYPRLAND_NO_SD_VARS
