#!/usr/bin/env bash

# shellcheck disable=SC1091
source "${LIB_DIR:-$HOME/.local/lib}/hypr/globalcontrol.sh"

gamemode_state_file="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}/gamemode.conf"
focusmode_state_file="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}/focusmode.conf"

write_gamemode_state() {
  mkdir -p "$(dirname "${gamemode_state_file}")"
  cat >"${gamemode_state_file}" <<'STATE'
# Generated by gamemode.sh
animations:enabled = 0
decoration:shadow:enabled = 0
decoration:blur:xray = 1
decoration:blur:enabled = 0
general:gaps_in = 0
general:gaps_out = 0
general:border_size = 1
decoration:rounding = 0
decoration:active_opacity = 1
decoration:inactive_opacity = 1
decoration:fullscreen_opacity = 1
layerrule = animation none, match:namespace waybar
layerrule = animation none, match:namespace notifications
layerrule = animation none, match:namespace swww-daemon
layerrule = animation none, match:namespace rofi
windowrule = opaque 1, match:class (.*)
STATE
}

disable_gamemode_state() {
  rm -f "${gamemode_state_file}"
}

gamemode_enabled() {
  [[ -f "${gamemode_state_file}" ]] || [[ "$(state_get HYPR_GAMEMODE 0)" == "1" ]]
}

if gamemode_enabled; then
  disable_gamemode_state
  state_set "HYPR_GAMEMODE" "0" "staterc"
else
  write_gamemode_state
  rm -f "${focusmode_state_file}"
  state_set "HYPR_GAMEMODE" "1" "staterc"
  state_set "HYPR_FOCUSMODE" "0" "staterc"
fi

hyprctl reload config-only -q
