$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-green-light
$COLOR_SCHEME = prefer-light
$NVIM_SCHEME = aether
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = Adwaita
$CURSOR_SIZE = 30
$FONT = JetBrainsMono Nerd Font
$BAR_FONT = JetBrainsMono Nerd Font
$MENU_FONT = JetBrainsMono Nerd Font
$MONOSPACE_FONT = JetBrainsMono Nerd Font
$TERMINAL_FONT = JetBrainsMono Nerd Font
$NOTIFICATION_FONT = JetBrainsMono Nerd Font Mono

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(85b34c)
    col.inactive_border = rgba(a09080cc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgb(85b34c)
    col.border_inactive = rgba(a09080cc)
    col.border_locked_active = rgb(496c1e)
    col.border_locked_inactive = rgba(a09080cc)
}

decoration {
    rounding = 4
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
