background = "#1F2430"
foreground = "#FFFFFF"
cursor-color = "#bae67e"
cursor-text = "#0a320a"
selection-foreground = "#0A1010"
selection-background = "#FFFFFF"

colors = [
  "#191e2a",
  "#ed8274",
  "#4B7D7D",
  "#fad07b",
  "#6dcbfa",
  "#cfbafa",
  "#90e1c6",
  "#c7c7c7",
  "#686868",
  "#f28779",
  "#bae67e",
  "#ffd580",
  "#73d0ff",
  "#d4bfff",
  "#95e6cb",
  "#ffffff",
]
