#!/usr/bin/env bash
# Shared helpers for live Hyprland monitor management scripts.
# Sourced by system/monitor-*.sh entrypoints.

monitor_state_dir() {
  printf '%s\n' "${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}"
}

monitor_toggle_dir() {
  printf '%s\n' "$(monitor_state_dir)/monitor-toggles"
}

monitor_toggle_file() {
  local name="$1"
  printf '%s/%s.conf\n' "$(monitor_toggle_dir)" "${name}"
}

monitor_aggregate_file() {
  printf '%s\n' "$(monitor_state_dir)/monitor-toggles.conf"
}

monitor_lock_file() {
  printf '%s\n' "${HYPR_RUNTIME_DIR:-${XDG_RUNTIME_DIR:-/tmp}/hypr}/monitor-toggles.lock"
}

monitor_notify() {
  local summary="$1"
  local body="${2:-}"

  if declare -F send_ephemeral_notif >/dev/null 2>&1; then
    if [[ -n "${body}" ]]; then
      send_ephemeral_notif "hypr-monitor" -t 3000 -i "video-display" "${summary}" "${body}" >/dev/null 2>&1 || true
    else
      send_ephemeral_notif "hypr-monitor" -t 3000 -i "video-display" "${summary}" >/dev/null 2>&1 || true
    fi
    return 0
  fi

  if command -v notify-send >/dev/null 2>&1; then
    if [[ -n "${body}" ]]; then
      notify-send -t 3000 -i "video-display" "${summary}" "${body}" >/dev/null 2>&1 || true
    else
      notify-send -t 3000 -i "video-display" "${summary}" >/dev/null 2>&1 || true
    fi
  fi
}

monitor_with_lock() {
  local lock_file=""
  local lock_fd=""

  lock_file="$(monitor_lock_file)"
  mkdir -p "$(dirname "${lock_file}")" "$(monitor_toggle_dir)" "$(monitor_state_dir)" || return 1
  exec {lock_fd}>"${lock_file}"
  flock "${lock_fd}" || return 1
  "$@"
  local rc=$?
  flock -u "${lock_fd}" 2>/dev/null || true
  exec {lock_fd}>&-
  return "${rc}"
}

monitor_rebuild_toggles_unlocked() {
  local aggregate=""
  local tmp_file=""
  local fragment=""

  aggregate="$(monitor_aggregate_file)"
  mkdir -p "$(monitor_toggle_dir)" "$(dirname "${aggregate}")" || return 1
  tmp_file="$(mktemp "${aggregate}.tmp.XXXXXX")" || return 1

  {
    printf '# Generated by hyprshell monitor helpers. Do not edit manually.\n'
    printf '# Remove fragments from %s or use the monitor helper commands.\n\n' "$(monitor_toggle_dir)"
    while IFS= read -r -d '' fragment; do
      printf '# source-fragment: %s\n' "${fragment}"
      cat "${fragment}"
      printf '\n'
    done < <(find "$(monitor_toggle_dir)" -maxdepth 1 -type f -name '*.conf' -print0 2>/dev/null | sort -z)
  } >"${tmp_file}"

  mv -f -- "${tmp_file}" "${aggregate}"
}

monitor_rebuild_toggles() {
  monitor_with_lock monitor_rebuild_toggles_unlocked
}

monitor_set_fragment_unlocked() {
  local name="$1"
  local content="$2"
  local target=""
  local tmp_file=""

  target="$(monitor_toggle_file "${name}")"
  mkdir -p "$(dirname "${target}")" || return 1
  tmp_file="$(mktemp "${target}.tmp.XXXXXX")" || return 1
  printf '%s\n' "${content}" >"${tmp_file}"
  mv -f -- "${tmp_file}" "${target}"
  monitor_rebuild_toggles_unlocked
}

monitor_set_fragment() {
  monitor_with_lock monitor_set_fragment_unlocked "$@"
}

monitor_remove_fragment_unlocked() {
  local name="$1"
  rm -f -- "$(monitor_toggle_file "${name}")"
  monitor_rebuild_toggles_unlocked
}

monitor_remove_fragment() {
  monitor_with_lock monitor_remove_fragment_unlocked "$@"
}

monitor_fragment_exists() {
  [[ -f "$(monitor_toggle_file "$1")" ]]
}

monitor_reload() {
  if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] && command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null
  fi
}

monitor_is_internal_name() {
  [[ "${1:-}" =~ ^(eDP|LVDS) ]]
}

monitor_internal_name() {
  hyprctl monitors all -j 2>/dev/null \
    | jq -r '[.[] | select(.name | test("^(eDP|LVDS)"))][0].name // empty'
}

monitor_focused_name() {
  hyprctl monitors -j 2>/dev/null \
    | jq -r '([.[] | select(.focused == true)][0] // .[0]).name // empty'
}

monitor_external_active_name() {
  hyprctl monitors -j 2>/dev/null \
    | jq -r '[.[] | select((.name | test("^(eDP|LVDS)") | not) and (.disabled != true))][0].name // empty'
}

monitor_external_connected_name() {
  local output=""
  local status_file=""

  for status_file in /sys/class/drm/card*-*/status; do
    [[ -e "${status_file}" ]] || continue
    [[ "${status_file}" == *-eDP-*/status || "${status_file}" == *-LVDS-*/status ]] && continue
    [[ "$(<"${status_file}")" == "connected" ]] || continue
    output="${status_file%/status}"
    output="${output##*/}"
    output="${output#card*-}"
    printf '%s\n' "${output}"
    return 0
  done

  hyprctl monitors all -j 2>/dev/null \
    | jq -r '[.[] | select(.name | test("^(eDP|LVDS)") | not)][0].name // empty'
}

monitor_has_active_external() {
  [[ -n "$(monitor_external_active_name)" ]]
}

monitor_has_connected_external() {
  [[ -n "$(monitor_external_connected_name)" ]]
}

monitor_mode_for() {
  local output="$1"
  hyprctl monitors all -j 2>/dev/null \
    | jq -r --arg output "${output}" '
        [.[] | select(.name == $output)][0] as $m
        | if ($m.width // 0) > 0 and ($m.height // 0) > 0 and ($m.refreshRate // 0) > 0
          then "\($m.width)x\($m.height)@\($m.refreshRate)"
          else "preferred"
          end
      '
}

monitor_position_for() {
  local output="$1"
  hyprctl monitors -j 2>/dev/null \
    | jq -r --arg output "${output}" '
        [.[] | select(.name == $output)][0] as $m
        | if $m == null then "auto" else "\($m.x)x\($m.y)" end
      '
}

monitor_transform_for() {
  local output="$1"
  hyprctl monitors all -j 2>/dev/null \
    | jq -r --arg output "${output}" '[.[] | select(.name == $output)][0].transform // 0'
}

monitor_gdk_scale_for() {
  case "$1" in
    1) printf '1\n' ;;
    1.25) printf '1.25\n' ;;
    1.6) printf '1.75\n' ;;
    2) printf '2\n' ;;
    3) printf '3\n' ;;
    4) printf '4\n' ;;
    *) printf '%s\n' "$1" ;;
  esac
}

monitor_sanitize_name() {
  printf '%s\n' "$1" | tr -c 'A-Za-z0-9_.-' '_'
}
