#!/usr/bin/env bash
# One knob for apparent text size across the desktop, modelled on
# omarchy-display-text-size. Drives these settings in lockstep, all anchored to
# a 12px base:
#   • the bar's text scale        (TEXT_SIZE in staterc; quickshell watches it)
#   • GNOME/GTK text-scaling-factor (12px -> 1.0, quantized so the interface
#     font lands on a whole point size, so 16 -> 15pt/11pt = 1.3636)
# Every point size comes off one 10pt anchor (12px -> 10pt, pt = px * 10/12);
# only the rounding differs, and only where the consumer forces it:
#   • terminal font point size    (kept fractional — kitty and alacritty both
#     take a float, and truncating would quantize the smooth scale away)
#   • Qt font point size          (the same fractional value, written to
#     kdeglobals and qt6ct/qt5ct; Qt's logical DPI stays at 96, so scaling
#     QT_FONT_DPI on top of the point size would apply the factor twice)
#   • rofi font size              (integer, matching rofi_effective_font_scale;
#     the theme rasi files declare no font, so config.rasi is the only one that
#     needs writing)
#   • dunst font point size       (rendered by render/dunst.py with the same
#     truncating division as rofi, so a notification and a menu never land a
#     point apart; applying re-renders dunstrc)
set -euo pipefail

readonly -a TEXT_SIZES=(9 10 11 12 13 14 15 16 17 18 19 20)
[[ "${1:-}" == "--list" ]] && { printf '%s\n' "${TEXT_SIZES[*]}"; exit; }

source "${HYPR_LIB_DIR:-$HOME/.local/lib/hypr}/runtime/init.bash"

hypr_help_guard "Usage: hyprshell system/text-size [size|reset]
  (no args)   print the current text size, GTK factor, terminal size, and Qt size
  <size>      set text size in px (9-20); bar + GTK + terminals + Qt together
  --list      print available sizes
  reset       return all four to their defaults (12px / 1.0 / 10pt)" "$@"

hypr_runtime_require state

readonly MIN="${TEXT_SIZES[0]}"
readonly MAX="${TEXT_SIZES[-1]}"
readonly BASE_PX=12
readonly BASE_PT=10
readonly ROFI_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/config.rasi"
readonly GKEY_SCHEMA="org.gnome.desktop.interface"
readonly GKEY_NAME="text-scaling-factor"

# Point size of the GTK interface font, used to quantize the scaling factor so
# the rendered font lands on a whole point. Falls back to the GNOME default.
gtk_font_pt() {
  local name pt
  name="$(gsettings get "${GKEY_SCHEMA}" font-name 2>/dev/null || true)"
  pt="${name%\'}"
  pt="${pt##* }"
  [[ ${pt} =~ ^[0-9]+([.][0-9]+)?$ ]] && printf '%s\n' "${pt}" || printf '11\n'
}

term_pt_for() {
  awk -v size="$1" -v pt="${BASE_PT}" -v base="${BASE_PX}" \
    'BEGIN { printf "%.2f", size * pt / base }'
}

# Truncating, not rounding: rofi_effective_font_scale uses integer division, and
# a menu launched through the helpers must not differ from a bare rofi launch.
rofi_pt_for() {
  printf '%s\n' $(($1 * BASE_PT / BASE_PX))
}

# dunstrc is generated by render/dunst.py, which derives the size the same way
# rofi_pt_for does. Read the rendered value rather than recomputing it here, so
# this can never report a size dunst is not actually using.
dunst_pt_now() {
  local conf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc" pt=""
  [[ -r ${conf} ]] && pt="$(sed -nE \
    's/^[[:space:]]*font[[:space:]]*=.*[^0-9]([0-9]+)[[:space:]]*$/\1/p' \
    "${conf}" | head -1)"
  printf '%s\n' "${pt:--}"
}

factor_for() {
  awk -v size="$1" -v base="${BASE_PX}" -v font="$(gtk_font_pt)" \
    'BEGIN { printf "%.4f", int(font * size / base + 0.5) / font }'
}

# Qt apps ignore the GTK factor, so the point size is the only scale they get.
# Which file is read depends on the platform
# theme: qt6ct/qt5ct own the fonts when QT_QPA_PLATFORMTHEME points at them,
# kdeglobals when it does not — so keep both in step.
set_qt_fonts() {
  local size="$1" family="" mono=""
  command -v kwriteconfig6 >/dev/null 2>&1 || return 0
  family="$(hypr_config_value_from_layers FONT 2>/dev/null || true)"
  mono="$(hypr_config_value_from_layers MONOSPACE_FONT 2>/dev/null || true)"
  [[ -n "${family}" ]] || family="Cantarell"
  [[ -n "${mono}" ]] || mono="monospace"

  local ui="" fixed="" small=""
  ui="$(term_pt_for "${size}")"
  fixed="${ui}"
  small="$(awk -v size="${size}" -v pt="${BASE_PT}" -v base="${BASE_PX}" \
    'BEGIN { printf "%.2f", size * pt * 0.8 / base }')"
  local key=""
  for key in font menuFont toolBarFont; do
    kwriteconfig6 --file kdeglobals --group General --key "${key}" "${family},${ui},-1,5,400,0,0,0,0,0"
  done
  kwriteconfig6 --file kdeglobals --group General --key fixed "${mono},${fixed},-1,5,400,0,0,0,0,0"
  kwriteconfig6 --file kdeglobals --group General --key smallestReadableFont "${family},${small},-1,5,400,0,0,0,0,0"
  kwriteconfig6 --file kdeglobals --group WM --key activeFont "${family},${ui},-1,5,400,0,0,0,0,0"

  local tail="-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0" conf="" flavour=""
  for flavour in qt6ct qt5ct; do
    conf="${XDG_CONFIG_HOME:-$HOME/.config}/${flavour}/${flavour}.conf"
    [[ -f "${conf}" ]] || continue
    sed -i -E "s|^general=\".*\"|general=\"${family},${ui},${tail}\"|; s|^fixed=\".*\"|fixed=\"${mono},${fixed},${tail}\"|" "${conf}"
  done
}

# Family is left alone — that is fonts/font-sync.sh's job, which is also why
# only the trailing size is rewritten here.
set_rofi_size() {
  local pt="$1"

  [[ -f "${ROFI_CONF}" ]] || return 0
  sed -i -E "s/^([[:space:]]*font:[[:space:]]*\"[^\"]*[^0-9 ])[[:space:]]+[0-9]+([.][0-9]+)?\";/\1 ${pt}\";/" \
    "${ROFI_CONF}"
}

# Family is left alone — that is fonts/font-set.sh's job.
set_terminal_size() {
  local pt="$1"

  if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/kitty/kitty.conf" ]]; then
    sed -i -E "s/^font_size[[:space:]]+.*/font_size ${pt}/" \
      "${XDG_CONFIG_HOME:-$HOME/.config}/kitty/kitty.conf"
    pkill -USR1 -x kitty 2>/dev/null || true
  fi

  if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty.toml" ]]; then
    sed -i -E "s/^size[[:space:]]*=.*/size = ${pt}/" \
      "${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty.toml"
  fi
}

current_size() {
  local size
  size="$(state_get TEXT_SIZE "" 2>/dev/null || true)"
  [[ ${size} =~ ^[0-9]+$ ]] && printf '%s\n' "${size}" || printf '%s\n' "${BASE_PX}"
}

report() {
  local size; size="$(current_size)"
  printf 'text size   %spx\n' "${size}"
  printf 'gtk factor  %s\n' "$(gsettings get "${GKEY_SCHEMA}" "${GKEY_NAME}" 2>/dev/null || echo '-')"
  printf 'terminal    %spt\n' "$(term_pt_for "${size}")"
  printf 'rofi        %spt\n' "$(rofi_pt_for "${size}")"
  printf 'dunst       %spt\n' "$(dunst_pt_now)"
  printf 'kde ui      %spt\n' "$(term_pt_for "${size}")"
}

apply() {
  local size="$1"

  if [[ ! ${size} =~ ^[0-9]+$ ]] || ((size < MIN || size > MAX)); then
    echo "text-size: size must be an integer between ${MIN} and ${MAX}" >&2
    exit 1
  fi

  state_set TEXT_SIZE "${size}"
  gsettings set "${GKEY_SCHEMA}" "${GKEY_NAME}" "$(factor_for "${size}")" 2>/dev/null || true
  set_terminal_size "$(term_pt_for "${size}")"
  set_rofi_size "$(rofi_pt_for "${size}")"
  set_qt_fonts "${size}"
  # dunstrc is generated: re-render it
  hyprshell render/dunst.py >/dev/null 2>&1 || true
  print_log -sec "text-size" -stat "applied" "${size}px"
}

case "${1-}" in
  "") report ;;
  reset) apply "${BASE_PX}" ;;
  *) apply "$1" ;;
esac
