# Qutebrowser Pywal Colors
# Generated from pywal16
# Location: ~/.cache/wal/colors-qutebrowser.py
# Symlinked to: ~/.config/qutebrowser/pywal-colors.py

# Pywal16 color variables
background = '{background}'
foreground = '{foreground}'
cursor = '{cursor}'

color0 = '{color0}'
color1 = '{color1}'
color2 = '{color2}'
color3 = '{color3}'
color4 = '{color4}'
color5 = '{color5}'
color6 = '{color6}'
color7 = '{color7}'
color8 = '{color8}'
color9 = '{color9}'
color10 = '{color10}'
color11 = '{color11}'
color12 = '{color12}'
color13 = '{color13}'
color14 = '{color14}'
color15 = '{color15}'

# Semantic color assignments
bg = background
fg = foreground
accent = color4
urgent = color1
success = color2
warning = color3

# Border color
border = color4

# ============================================================================
# Apply Colors to Qutebrowser
# ============================================================================

# Completion widget
c.colors.completion.fg = fg
c.colors.completion.odd.bg = color0
c.colors.completion.even.bg = bg
c.colors.completion.category.fg = color4
c.colors.completion.category.bg = color0
c.colors.completion.category.border.top = color0
c.colors.completion.category.border.bottom = color0
c.colors.completion.item.selected.fg = bg
c.colors.completion.item.selected.bg = accent
c.colors.completion.item.selected.border.top = accent
c.colors.completion.item.selected.border.bottom = accent
c.colors.completion.item.selected.match.fg = color11
c.colors.completion.match.fg = color2
c.colors.completion.scrollbar.fg = fg
c.colors.completion.scrollbar.bg = bg

# Context menu
c.colors.contextmenu.disabled.bg = color0
c.colors.contextmenu.disabled.fg = color8
c.colors.contextmenu.menu.bg = bg
c.colors.contextmenu.menu.fg = fg
c.colors.contextmenu.selected.bg = accent
c.colors.contextmenu.selected.fg = bg

# Downloads
c.colors.downloads.bar.bg = bg
c.colors.downloads.start.fg = bg
c.colors.downloads.start.bg = color4
c.colors.downloads.stop.fg = bg
c.colors.downloads.stop.bg = color2
c.colors.downloads.error.fg = color1

# Hints (link following)
c.colors.hints.fg = bg
c.colors.hints.bg = color11
c.colors.hints.match.fg = color2

# Note: c.hints.border and c.hints.radius are set by qute-hypr-sync.py
# (generated by wal.qutebrowser.sh with Hyprland integration)

# Keyhint widget
c.colors.keyhint.fg = fg
c.colors.keyhint.suffix.fg = fg
c.colors.keyhint.bg = bg

# Messages
c.colors.messages.error.fg = bg
c.colors.messages.error.bg = color1
c.colors.messages.error.border = color1
c.colors.messages.warning.fg = bg
c.colors.messages.warning.bg = color3
c.colors.messages.warning.border = color3
c.colors.messages.info.fg = fg
c.colors.messages.info.bg = bg
c.colors.messages.info.border = color0

# Prompts
c.colors.prompts.fg = fg
c.colors.prompts.bg = bg
c.colors.prompts.border = color0
c.colors.prompts.selected.fg = bg
c.colors.prompts.selected.bg = accent
# Note: colors.prompts.selected.border was removed in qutebrowser 3.x
# Border color is now derived from bg automatically

# Statusbar (bottom bar)
c.colors.statusbar.normal.fg = fg
c.colors.statusbar.normal.bg = bg
c.colors.statusbar.insert.fg = bg
c.colors.statusbar.insert.bg = color4
c.colors.statusbar.passthrough.fg = bg
c.colors.statusbar.passthrough.bg = color12
c.colors.statusbar.private.fg = bg
c.colors.statusbar.private.bg = color0
c.colors.statusbar.command.fg = fg
c.colors.statusbar.command.bg = bg
c.colors.statusbar.command.private.fg = fg
c.colors.statusbar.command.private.bg = bg
c.colors.statusbar.caret.fg = bg
c.colors.statusbar.caret.bg = color5
c.colors.statusbar.caret.selection.fg = bg
c.colors.statusbar.caret.selection.bg = color4
c.colors.statusbar.progress.bg = accent
c.colors.statusbar.url.fg = fg
c.colors.statusbar.url.error.fg = color1
c.colors.statusbar.url.hover.fg = color12
c.colors.statusbar.url.success.http.fg = color2
c.colors.statusbar.url.success.https.fg = color2
c.colors.statusbar.url.warn.fg = color3

# Tabs
c.colors.tabs.bar.bg = bg
c.colors.tabs.indicator.start = color4
c.colors.tabs.indicator.stop = color2
c.colors.tabs.indicator.error = color1

# Even tabs
c.colors.tabs.even.fg = fg
c.colors.tabs.even.bg = color0

# Odd tabs
c.colors.tabs.odd.fg = fg
c.colors.tabs.odd.bg = bg

# Selected tabs (even)
c.colors.tabs.selected.even.fg = bg
c.colors.tabs.selected.even.bg = accent

# Selected tabs (odd)
c.colors.tabs.selected.odd.fg = bg
c.colors.tabs.selected.odd.bg = accent

# Pinned tabs
c.colors.tabs.pinned.even.fg = color7
c.colors.tabs.pinned.even.bg = color8
c.colors.tabs.pinned.odd.fg = color7
c.colors.tabs.pinned.odd.bg = color0
c.colors.tabs.pinned.selected.even.fg = bg
c.colors.tabs.pinned.selected.even.bg = accent
c.colors.tabs.pinned.selected.odd.fg = bg
c.colors.tabs.pinned.selected.odd.bg = accent

# Web page colors
c.colors.webpage.bg = bg
c.colors.webpage.preferred_color_scheme = 'dark'
c.colors.webpage.darkmode.enabled = True
c.colors.webpage.darkmode.policy.images = 'never'
c.colors.webpage.darkmode.threshold.foreground = 150
c.colors.webpage.darkmode.threshold.background = 100
c.colors.webpage.darkmode.algorithm = 'brightness-rgb'

# Tooltip
c.colors.tooltip.fg = fg
c.colors.tooltip.bg = bg

# ============================================================================
# Fonts (matching your system)
# ============================================================================

c.fonts.default_family = 'CaskaydiaCove Nerd Font Mono'
c.fonts.default_size = '11pt'

c.fonts.completion.entry = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.completion.category = 'bold 11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.debug_console = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.prompts = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.statusbar = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.messages.error = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.messages.info = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.messages.warning = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.tabs.selected = 'bold 11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.tabs.unselected = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.hints = 'bold 11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.keyhint = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.downloads = '11pt "CaskaydiaCove Nerd Font Mono"'
c.fonts.contextmenu = '11pt "CaskaydiaCove Nerd Font Mono"'

# ============================================================================
# Additional Styling
# ============================================================================

# Hints styling
# Note: border and radius are set by qute-hypr-sync.py (Hyprland integration)
c.hints.border = '1px solid ' + border  # Border color from pywal

# Tabs padding (matching waybar style)
c.tabs.padding = {{'top': 4, 'bottom': 4, 'left': 5, 'right': 5}}
c.tabs.indicator.width = 3

# Scrollbar
c.scrolling.bar = 'when-searching'

# Status bar position
c.statusbar.position = 'bottom'

# Note: Color mode (dark/light) is handled by qute-hypr-sync.py

print('Pywal colors loaded successfully!')
print(f'Background: {{background}}')
print(f'Foreground: {{foreground}}')
print(f'Accent: {{color4}}')
