$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$GTK_THEME = Adwaita
$ICON_THEME = Fluent-orange-light
$COLOR_SCHEME = prefer-light
$FONT = CodeNewRoman Nerd Font
$BAR_FONT = CodeNewRoman Nerd Font
$MENU_FONT = CodeNewRoman Nerd Font
$MONOSPACE_FONT = CodeNewRoman Nerd Font
$NOTIFICATION_FONT = CodeNewRoman Nerd Font Mono

$CURSOR_THEME = Adwaita
$CURSOR_SIZE = 30

general {
    gaps_in = 5
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(8F6518ff)
    col.inactive_border = rgba(BFAC93cc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(B85C1Eff)
    col.border_inactive = rgba(BFAC93cc)
    col.border_locked_active = rgba(8F6518ff)
    col.border_locked_inactive = rgba(BFAC93cc)
}

decoration {
    rounding = 3
    shadow:enabled = false

    blur {
        enabled = yes
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
