background = "#161616"
foreground = "#ffffff"
cursor-color = "#33b1ff"
cursor-text = "#161616"
selection-foreground = "#161616"
selection-background = "#33b1ff"

colors = [
  "#262626",
  "#ee5396",
  "#42be65",
  "#ffe97b",
  "#33b1ff",
  "#ff7eb6",
  "#3ddbd9",
  "#dde1e6",
  "#393939",
  "#ee5396",
  "#42be65",
  "#ffe97b",
  "#33b1ff",
  "#ff7eb6",
  "#3ddbd9",
  "#ffffff",
]
