$HOME/.config/alacritty/theme.toml

[colors.primary]
foreground = "#3f3f3f"
background = "#f3f3f3"

[colors.cursor]
text = "#f3f3f3"
cursor = "#3f3f3f"

[colors.selection]
text = "#3f3f3f"
background = "#bbddff"

[colors.normal]
black = "#3f3f3f"
red = "#295fb0"
green = "#509be8"
yellow = "#295fb0"
blue = "#509bee"
magenta = "#70aae5"
cyan = "#bbddff"
white = "#c1c1c1"

[colors.bright]
black = "#3f3f3f"
red = "#509bee"
green = "#70aae5"
yellow = "#70aae5"
blue = "#509bee"
magenta = "#295fb0"
cyan = "#bbddff"
white = "#e6e6e6"
