background = "#1B1E28"
foreground = "#A6ACCD"
cursor-color = "#A6ACCD"
cursor-text = "#060605"
selection-foreground = "#1B1E28"
selection-background = "#FFF8F0"

colors = [
  "#171922",
  "#D0679D",
  "#5DE4C7",
  "#FFFAC2",
  "#ADD7FF",
  "#FCC5E9",
  "#89DDFF",
  "#A6ACCD",
  "#506477",
  "#D0679D",
  "#5DE4C7",
  "#FFFAC2",
  "#ADD7FF",
  "#FAE4FC",
  "#89DDFF",
  "#E4F0FB",
]
