$HOME/.config/rofi/theme.rasi
* {
    background:             #122D41B3;
    background-alpha:       #122D4159;
    foreground:             #CCE9FFE6;
    border:                 #7F9FC2E6;
    accent:                 #376FABE6;
    selected-background:    #AACBF080;
    selected-foreground:    #9FD6B0E6;
    separator:              #7F9FC240;
    urgent:                 #F6BAC1FF;
    active:                 #9AC5E6FF;
}
