$HOME/.config/rofi/theme.rasi
* {
    background:             #1B1E28B3;
    background-alpha:       #1B1E2859;
    foreground:             #CCE9FFE6;
    border:                 #7F9FC2E6;
    accent:                 #376FABE6;
    selected-background:    #AACBF080;
    selected-foreground:    #9FD6B0E6;
    separator:              #7F9FC240;
    urgent:                 #F6BAC1FF;
    active:                 #9AC5E6FF;
}
