$HOME/.config/rofi/theme.rasi
* {
    background:          #122D41B3;
    foreground:          #CCE9FFE6;
    border:              #7F9FC2E6;
    accent:              #376FABE6;
    selected-background: #AACBF0CC;
    selected-foreground: #D3DCE6FF;
    separator:           #7F9FC240;
    urgent:              #D3DCE6FF;
    active:              #9AC5E6FF;
    separatorcolor:      transparent;
    border-color:        transparent;
}
