#!/usr/bin/env bash
# Shared hyprlock layout/runtime helpers.
find_filepath() {
  local filename="${1:-default}"
  local search_name="${filename%.conf}.conf"
  local candidate extra_dir

  if [[ "${filename}" == */* ]] && [[ -f "${filename}" ]]; then
    printf '%s\n' "${filename}"
    return 0
  fi

  print_log -sec "hyprlock" -stat "Searching for layout" "${search_name}"

  for candidate in \
    "${HYPRLOCK_USER_DIR}/${search_name}" \
    "${HYPRLOCK_SHARED_DIR}/${search_name}"; do
    if [[ -f "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done

  extra_dir="${HYPRLOCK_CONF_DIR:-}"
  if [[ -n "${extra_dir}" ]] && [[ "${extra_dir}" != "${HYPRLOCK_USER_DIR}" ]] && [[ "${extra_dir}" != "${HYPRLOCK_SHARED_DIR}" ]]; then
    candidate="${extra_dir}/${search_name}"
    if [[ -f "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  fi

  return 1
}

check_and_sanitize_process() {
  local unit_name="${1:-${HYPRLOCK_SCOPE_NAME}}"
  if systemctl --user is-active "${unit_name}" >/dev/null 2>&1; then
    systemctl --user stop "${unit_name}" >/dev/null 2>&1
  fi
}

reload_hyprlock() {
  local unit_name="${1:-${HYPRLOCK_SCOPE_NAME}}"

  if systemctl --user is-active "${unit_name}" >/dev/null 2>&1; then
    systemctl --user kill -s USR2 "${unit_name}" >/dev/null 2>&1
  else
    pkill -USR2 hyprlock >/dev/null 2>&1
  fi
}

append_label_to_file() {
  local file="${1}"

  cat <<EOF >>"${file}"
label {
  text = PREVIEW! Press a key or swipe to exit.
  color = \$foreground
  font_size = 50
  position = 0, 0
  halign = center
  valign = top
  zindex = 6
}

label {
  text = PREVIEW! Press a key or swipe to exit.
  color = \$foreground
  font_size = 50
  position = 0, 0
  halign = center
  valign = bottom
  zindex = 6
}

label {
  text = PREVIEW! Press a key or swipe to exit.
  color = \$foreground
  font_size = 50
  position = 0, 0
  halign = center
  valign = center
  zindex = 6
}

EOF
}

layout_test() {
  print_log -sec "hyprlock" -stat "Test" "Please swipe,press a key or click to exit."
  local hyprlock_conf_name="${*:-${1}}"
  check_and_sanitize_process
  hyprlock_conf_path=$(find_filepath "${hyprlock_conf_name}")
  if [ -z "${hyprlock_conf_path}" ]; then
    print_log -sec "hyprlock" -stat "Error" "Layout ${hyprlock_conf_name} not found."
    exit 1
  fi
  sleep 2
  local temp_path="${XDG_RUNTIME_DIR}/hyprlock-test.conf"
  generate_conf "${hyprlock_conf_path}" "${temp_path}"
  append_label_to_file "${temp_path}"
  app2unit.sh -S both -u "${HYPRLOCK_SCOPE_NAME}" -t scope -- hyprlock --no-fade-in --immediate-render --grace 99999999 -c "${temp_path}"
  rm -f "${temp_path}"
}

rofi_test_preview() {
  local hyprlock_conf_name="${*:-${1}}"
  local unit_name="${XDG_SESSION_DESKTOP:-unknown}-lockscreen-preview.scope"
  check_and_sanitize_process "${unit_name}"
  send_ephemeral_notif "hypr-hyprlock-preview" "Hyprlock layout: ${hyprlock_conf_name}" "Please swipe, press a key or click to exit." \
    -i "system-lock-screen" -t 3000 \
    -r 9
  app2unit.sh -S both -u "${unit_name}" -t scope -- hyprlock.sh --test "${hyprlock_conf_name}"
}

generate_conf() {
  local path="${1:-${HYPRLOCK_SHARED_DIR}/default.conf}"
  local target_file="${2:-${HYPR_CONFIG_HOME}/hyprlock.conf}"
  local hyprlock_conf="${HYPR_DATA_HOME:-${XDG_DATA_HOME}/hypr}/hyprlock.conf"
  local layout_path
  local source_conf

  layout_path="$(hypr_compact_path "${path}")"
  source_conf="$(hypr_compact_path "${hyprlock_conf}")"

  cat <<CONF >"${target_file}"
#! █░█ █▄█ █▀█ █▀█ █░░ █▀█ █▀▀ █▄▀
#! █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █░█


#*  Hyprlock Configuration File 
# Please do not edit this file manually.
# Follow the instructions below on how to make changes.

#* Hyprlock active layout path:
# Set the layout file used by Hyprlock.
# Shared layouts live in '\$XDG_DATA_HOME/hypr/hyprlock/'.
# Set this to a full layout path if you want to override the current selection.
\$LAYOUT_PATH=${layout_path}

#*  Managed layout declaration 
# This file is generated by 'hyprshell hyprlock.sh'.
# Layout selection is normally managed through the Hyprlock selector and state.
# Manual edits here will be overwritten the next time the layout is regenerated.

#*  All boilerplate configurations are handled by hyprshell 
source = ${source_conf}

#*  Making a custom layout 
# Put custom layouts in '\$XDG_CONFIG_HOME/hypr/hyprlock/' or shared layouts in
# '\$XDG_DATA_HOME/hypr/hyprlock/'.
# To use a custom layout, select it through 'hyprshell hyprlock.sh --select' or
# point '\$LAYOUT_PATH' at the full path to the layout file.

#*  Command Variables 
# Shared command variables are defined in '\$XDG_DATA_HOME/hypr/hyprlock.conf'.
# The shared boilerplate provides the following variables:
#
# \$BACKGROUND_PATH
# - Path to the current wallpaper image used by Hyprlock layouts.
#
# \$SPLASH_CMD
# - Fallback splash command when a layout wants a single dynamic text source.
#
# \$MPRIS_TEXT
# - Combined media text from the active player.
# - Useful for simple single-label media layouts.
#
# \$MPRIS_TITLE
# - Current media title from the active player.
#
# \$MPRIS_ARTIST
# - Current media artist from the active player.
#
# \$MPRIS_SOURCE
# - Current media source or player name.
#
# \$MPRIS_STATUS
# - Current playback status, such as Playing or Paused.
#
# \$MPRIS_LENGTH
# - Current media length text from the Hyprlock helper.
#
# \$MPRIS_IMAGE
# - Cached artwork path for the active media item.
#
# \$MPRIS_BLURRED
# - Blurred version of the cached artwork path.
#
# \$PROFILE_IMAGE
# - Cached profile image path used by avatar-style layouts.
#
# \$GREET_TEXT
# - Greeting text that changes with the time of day.
#
# \$GREET_ICON
# - Greeting icon that changes with the time of day.
#
# \$WEATHER_CMD
# - Inline weather command using wttr.in output.
#
# \$WEATHER
# - Detailed weather command from 'wttr.sh'.
#
# \$LOCATION
# - Current location label from 'wttr.sh'.
#
# \$BATTERY_ICON
# - Battery icon command for battery-capable systems.

CONF
}

# hyprlock selector
fn_select() {
  # List available .conf files from user overrides first, then shared stock.
  local layout_items
  local -A seen_layouts=()
  local layout_dir layout_path layout_name
  local -a rofi_args
  for layout_dir in "${HYPRLOCK_USER_DIR}" "${HYPRLOCK_SHARED_DIR}"; do
    [[ -d "${layout_dir}" ]] || continue
    while IFS= read -r -d '' layout_path; do
      layout_name="$(basename "${layout_path}" .conf)"
      [[ "${layout_name}" == "theme" || "${layout_name}" == "colors" ]] && continue
      [[ -n "${seen_layouts[${layout_name}]:-}" ]] && continue
      seen_layouts["${layout_name}"]=1
      layout_items+="${layout_name}"$'\n'
    done < <(find -L "${layout_dir}" -maxdepth 1 -type f -name '*.conf' -print0 | sort -z)
  done

  if [ -z "$layout_items" ]; then
    send_ephemeral_notif "hypr-hyprlock-error" -t 3000 -i "preferences-desktop-display" "Error" "No .conf files found in ${HYPRLOCK_USER_DIR} or ${HYPRLOCK_SHARED_DIR}"
    exit 1
  fi

  layout_items="${layout_items}"

  rofi_build_standard_menu_args \
    rofi_args \
    "Select hyprlock layout" \
    "  Hyprlock Layout" \
    "${ROFI_HYPRLOCK_STYLE:-clipboard}" \
    "${ROFI_HYPRLOCK_SCALE}" \
    "${ROFI_HYPRLOCK_FONT:-$ROFI_FONT}"
  rofi_args+=(
    -select "${HYPRLOCK_LAYOUT}"
    -on-selection-changed "hyprshell hyprlock.sh --test-preview  \"{entry}\""
  )

  selected_layout=$(awk -F/ '{print $NF}' <<<"$layout_items" \
    | rofi "${rofi_args[@]}")

  if [ -z "$selected_layout" ]; then
    echo "No selection made"
    exit 0
  fi

  state_set "HYPRLOCK_LAYOUT" "${selected_layout}" "staterc"
  local hyprlock_conf_path
  hyprlock_conf_path=$(find_filepath "${selected_layout}")
  generate_conf "$hyprlock_conf_path"
  "${HYPR_LIB_DIR}/font.sh" resolve "$hyprlock_conf_path"
  fn_profile

  # Notify the user
  send_ephemeral_notif "hypr-hyprlock-layout" -t 2000 -i "system-lock-screen" "Hyprlock layout" "${selected_layout}"
}
