$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Fluent-green-dark
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = citruszest
$NVIM_VARIANT =
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false

$CURSOR_THEME = Hackneyed-Dark
$CURSOR_SIZE = 24
$FONT = ShureTechMono Nerd Font
$BAR_FONT = ShureTechMono Nerd Font
$MENU_FONT = ShureTechMono Nerd Font
$MONOSPACE_FONT = ShureTechMono Nerd Font
$TERMINAL_FONT = ShureTechMono Nerd Font
$NOTIFICATION_FONT = ShureTechMono Nerd Font Mono

# Theme variables above are the primary inputs used by theme.switch.sh.

general {
    gaps_in = 7
    gaps_out = 14
    border_size = 4
    col.active_border = rgba(FADA16ff) 
    col.inactive_border = rgba(1F5322ff)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(5032acff)
    col.border_inactive = rgba(4DBD4Fff)
    col.border_locked_active = rgba(5032acff)
    col.border_locked_inactive = rgba(4DBD4Fff)
}

decoration {
    rounding = 0

    shadow {
        enabled = true
        range = 0
        offset = 5 5
        render_power = 4
        color = 0xe6e5e4e2
    }


    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
