background = "#181818"
foreground = "#E4E4E4"
cursor-color = "#FFDD33"
cursor-text = "#a56df2"
selection-foreground = "#181818"
selection-background = "#FADA16"

colors = [
  "#181818",
  "#F43841",
  "#73D936",
  "#FFDD33",
  "#96A6C8",
  "#9E95C7",
  "#95A99F",
  "#F5F5F5",
  "#52494E",
  "#F43841",
  "#73D936",
  "#FFDD33",
  "#96A6C8",
  "#9E95C7",
  "#95A99F",
  "#FFFFFF",
]
