$HOME/.config/rofi/theme.rasi
* {
    background:            #000000e6;
    foreground:            #ffffffff;
    border:                #ffa6c2ff;
    accent:                #f5e0dcff;
    selected-background:   #fada16ff;
    selected-foreground:   #000000ff;
    separator:             #80808080;
    urgent:                #ffa6c2ff;
    active:                #f5e0dcff;
    separatorcolor:     transparent;
    border-color:       transparent;
}
