#!/usr/bin/env bash
# wal.qutebrowser.sh - Generate qutebrowser config with dynamic settings

configDir="${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser"
cacheDir="${XDG_CACHE_HOME:-$HOME/.cache}/wal"
stateDir="${XDG_STATE_HOME:-$HOME/.local/state}/hypr"

# Create config directory if needed
mkdir -p "$configDir"

# ============================================================================
# Get Hyprland Border Radius
# ============================================================================

if command -v hyprctl &>/dev/null; then
    hypr_border=$(hyprctl -j getoption decoration:rounding 2>/dev/null | grep -o '"int": [0-9]*' | awk '{print $2}')
    if [ -z "$hypr_border" ] || [ "$hypr_border" = "null" ]; then
        hypr_border=4  # Default fallback
    fi
else
    hypr_border=4  # Default fallback
fi

# ============================================================================
# Get Color Mode from staterc
# ============================================================================

color_mode=2  # Default to Dark mode
if [ -f "$stateDir/staterc" ]; then
    color_mode=$(grep 'enableWallDcol=' "$stateDir/staterc" | sed 's/enableWallDcol=//;s/"//g')
    # Validate it's a number
    if ! [[ "$color_mode" =~ ^[0-3]$ ]]; then
        color_mode=2
    fi
fi

# Color mode names for logging
case "$color_mode" in
    0) color_mode_name="Theme" ;;
    1) color_mode_name="Auto" ;;
    2) color_mode_name="Dark" ;;
    3) color_mode_name="Light" ;;
    *) color_mode_name="Unknown" ;;
esac

# ============================================================================
# Generate Dynamic Config Snippet
# ============================================================================

cat > "$configDir/qute-hypr-sync.py" << PYEOF
# Auto-generated by wal.qutebrowser.sh
# DO NOT EDIT MANUALLY - This file is regenerated on theme change

# Hyprland Integration
hypr_border = ${hypr_border}  # Border radius from Hyprland
color_mode = ${color_mode}     # Color mode from staterc (0=Theme, 1=Auto, 2=Dark, 3=Light)
border_radius = '${hypr_border}px'

# Color mode names
color_mode_names = {0: 'Theme', 1: 'Auto', 2: 'Dark', 3: 'Light'}
color_mode_name = color_mode_names.get(color_mode, 'Unknown')

# Apply border radius to hints
c.hints.radius = hypr_border

# Note: Border color (c.hints.border) is set by pywal-colors.py

# Apply color mode to webpage preferences
if color_mode == 0:  # Theme mode
    # Use theme colors, respect system preference
    pass
elif color_mode == 1:  # Auto mode
    c.colors.webpage.preferred_color_scheme = 'auto'
    c.colors.webpage.darkmode.enabled = True
elif color_mode == 2:  # Dark mode
    c.colors.webpage.preferred_color_scheme = 'dark'
    c.colors.webpage.darkmode.enabled = True
elif color_mode == 3:  # Light mode
    c.colors.webpage.preferred_color_scheme = 'light'
    c.colors.webpage.darkmode.enabled = False

# Log for debugging
print(f'Hyprland sync: border_radius={hypr_border}px, color_mode={color_mode_name} ({color_mode})')
PYEOF

# ============================================================================
# Log Result
# ============================================================================

echo "✓ Qutebrowser sync: border_radius=${hypr_border}px, color_mode=${color_mode_name} (${color_mode})"

# ============================================================================
# Reload Qutebrowser (if running)
# ============================================================================

# Check if qutebrowser is running
if pgrep -x qutebrowser >/dev/null; then
    # Send SIGUSR1 to reload config (if qutebrowser supports it)
    # Or we can use qutebrowser's IPC
    if command -v qutebrowser &>/dev/null; then
        # Try to reload config via command
        qutebrowser ':config-source' 2>/dev/null || true
    fi
fi
