#!/usr/bin/env python3
# Renderer: GIMP gimp.css (palette-derived @define-color overrides for GIMP's Default theme).
# Output: ~/.cache/hypr/render/gimp/gimp.css

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import atomic_write, cache_hit, cache_store
from _roles import hex_to_rgb, luminance

PALETTE = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else
               os.environ.get("HYPR_STATE_HOME",
                              os.path.expanduser("~/.local/state/hypr")) + "/active-palette.json")
OUT_DIR = Path(os.environ.get("HYPR_CACHE_HOME",
                              os.path.expanduser("~/.cache/hypr"))) / "render" / "gimp"
OUT_FILE = OUT_DIR / "gimp.css"

APP = "gimp"

def rgb(c):
    r, g, b = hex_to_rgb(c)
    return f"rgb({r},{g},{b})"

def rgba(c, a):
    r, g, b = hex_to_rgb(c)
    return f"rgba({r},{g},{b},{a})"

def clamp(v):
    return max(0, min(255, v))

def shift(c, offset):
    r, g, b = (clamp(x + offset) for x in hex_to_rgb(c))
    return f"rgb({r},{g},{b})"

def blend(c1, c2, w):
    r1, g1, b1 = hex_to_rgb(c1)
    r2, g2, b2 = hex_to_rgb(c2)
    r = (r1 * (100 - w) + r2 * w) // 100
    g = (g1 * (100 - w) + g2 * w) // 100
    b = (b1 * (100 - w) + b2 * w) // 100
    return f"rgb({clamp(r)},{clamp(g)},{clamp(b)})"

def main():
    if not PALETTE.is_file():
        sys.exit(f"render/gimp: missing {PALETTE}")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    p = json.loads(PALETTE.read_text())
    bg, fg = p["bg"], p["fg"]

    hasher = hashlib.sha256()
    hasher.update(PALETTE.read_bytes())
    hasher.update(Path(__file__).read_bytes())
    h = hasher.hexdigest()[:16]

    # Resolve newest GIMP 3.x config dir for staging
    gimp_base = Path(os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))) / "GIMP"
    gimp_dir = None
    if gimp_base.is_dir():
        candidates = sorted([d for d in gimp_base.iterdir() if d.is_dir() and d.name.startswith("3.")])
        if candidates:
            gimp_dir = candidates[-1]

    if cache_hit(APP, h) and OUT_FILE.exists():
        return

    is_dark = luminance(bg) < 0.5
    sign = 1 if is_dark else 1  # both branches shift toward darker (fix from earlier session)

    widget_bg        = shift(bg, -18)
    extreme_bg       = shift(bg, -24)
    selected         = shift(bg, -30)
    extreme_selected = shift(bg, -5)
    border           = shift(bg, -34)
    strong_border    = shift(bg, -20)
    stronger_border  = shift(bg, 15)
    edge_border      = shift(bg, -34)
    hover            = shift(bg, 40 if is_dark else -40)
    dimmed_fg        = blend(fg, bg, 40)
    disabled_fg      = blend(fg, bg, 45)
    disabled_button  = blend(fg, bg, 60)
    scrollbar_slider = blend(fg, bg, 30)
    scrollbar_trough = rgb(bg)
    ruler            = rgba(bg, "0.3")
    fg_rgb           = rgb(fg)
    bg_rgb           = rgb(bg)

    css = f"""/* Auto-generated by render/gimp */

@define-color fg-color               {fg_rgb};
@define-color bg-color               {bg_rgb};
@define-color border-color           {border};
@define-color dimmed-fg-color        {dimmed_fg};
@define-color disabled-fg-color      {disabled_fg};
@define-color disabled-button-color  {disabled_button};
@define-color hover-color            {hover};
@define-color widget-bg-color        {widget_bg};
@define-color selected-color         {selected};
@define-color extreme-bg-color       {extreme_bg};
@define-color extreme-selected-color {extreme_selected};
@define-color strong-border-color    {strong_border};
@define-color stronger-border-color  {stronger_border};
@define-color edge-border-color      {edge_border};
@define-color scrollbar-slider-color {scrollbar_slider};
@define-color scrollbar-trough-color {scrollbar_trough};
@define-color ruler-color            {ruler};
"""

    atomic_write(OUT_FILE, css)

    cache_store(APP, h)

if __name__ == "__main__":
    main()
