#!/usr/bin/env bash
set -euo pipefail
PALETTE_ARG="${1:-}"
. "$(dirname "$0")/_lib.sh"
render_init hyprlock colors.conf

hash="$(render_input_hash)"
render_should_skip "${hash}" && exit 0

tmp="$(render_temp)"
trap 'rm -f "${tmp}"' EXIT

PALETTE="${PALETTE}" python3 - > "${tmp}" <<'PY'
import json, os
p = json.load(open(os.environ["PALETTE"]))
def rgb(h):
    h = h.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
ALPHA = "66"  # 40%

print("# Autogenerated hyprlock colors (RGB 0-255)\n")
for i, c in enumerate(p["colors"]):
    r, g, b = rgb(c)
    print(f"$c{i}.r = {r}")
    print(f"$c{i}.g = {g}")
    print(f"$c{i}.b = {b}")
    print(f"$color{i} = rgb({r}, {g}, {b})")
    print()
for short, key, long in (("bg", "bg", "background"), ("fg", "fg", "foreground"), ("cx", "cursor", "cursor")):
    if key not in p:
        continue
    r, g, b = rgb(p[key])
    print(f"${short}.r = {r}")
    print(f"${short}.g = {g}")
    print(f"${short}.b = {b}")
    print(f"${long} = rgb({r}, {g}, {b})")
    print()
print("# Alpha (40% = 0x66)")
for i, c in enumerate(p["colors"]):
    r, g, b = rgb(c)
    print(f"$color{i}_alpha = rgba({r:02x}{g:02x}{b:02x}{ALPHA})")
print()
for short, key in (("background", "bg"), ("foreground", "fg")):
    r, g, b = rgb(p[key])
    print(f"${short}_alpha = rgba({r:02x}{g:02x}{b:02x}{ALPHA})")
PY

render_commit "${tmp}" "${hash}"
trap - EXIT
