#!/usr/bin/env bash
set -euo pipefail
PALETTE_ARG="${1:-}"
. "$(dirname "$0")/_lib.sh"
# Pack hypr.theme is the pack manifest (sourced elsewhere as hyprland config), not
# a colors override; do not full-replace from it. Always derive.
render_init hypr colors.conf hypr.theme

hash="$(render_input_hash)"
render_should_skip "${hash}" && exit 0

tmp="$(render_temp)"
trap 'rm -f "${tmp}"' EXIT

mapfile -t C < <(jq -r '.bg, .fg, (.cursor // .fg), (.colors[])' "${PALETTE}")
bg="${C[0]}" fg="${C[1]}" cursor="${C[2]}"
c=("${C[@]:3}")

src="theme:${HYPR_THEME:-unknown}"
[[ -f "${PALETTE}" ]] && src="$(jq -r '.source' "${PALETTE}")"

mode="$(jq -r '.mode // ""' "${PALETTE}")"
source_field="$(jq -r '.source // ""' "${PALETTE}")"

# Border source of truth:
#   theme mode     -> pack's hypr.theme verbatim (no border directives if the pack omits them)
#   wallpaper mode -> derived from palette
emit_borders() {
  if [[ "${mode}" == "theme" && "${source_field}" == theme:* ]]; then
    local pack_hypr="${HOME}/.config/hypr/themes/${source_field#theme:}/hypr.theme"
    [[ -f "${pack_hypr}" ]] || return 0
    awk '
      /^[[:space:]]*(general|group)[[:space:]]*\{/ { in_block=1; block_buf=""; matched=0; print; next }
      in_block && /^[[:space:]]*\}/ { if (matched) print block_buf; print; in_block=0; next }
      in_block {
        if ($0 ~ /^[[:space:]]*col\.(active_border|inactive_border|border_(active|inactive|locked_active|locked_inactive))[[:space:]]*=/) {
          block_buf = block_buf $0 "\n"; matched=1
        }
        next
      }
      { next }
    ' "${pack_hypr}"
  else
    local active="${c[4]#\#}ff"
    local inactive_bg="${c[0]#\#}cc"
    local inactive_fg="${c[8]#\#}cc"
    cat <<EOF
general {
    col.active_border = rgba(${active}) rgba(${active}) 45deg
    col.inactive_border = rgba(${inactive_bg}) rgba(${inactive_fg}) 45deg
}

group {
    col.border_active = rgba(${active}) rgba(${active}) 45deg
    col.border_inactive = rgba(${inactive_bg}) rgba(${inactive_fg}) 45deg
    col.border_locked_active = rgba(${active}) rgba(${active}) 45deg
    col.border_locked_inactive = rgba(${inactive_bg}) rgba(${inactive_fg}) 45deg
}
EOF
  fi
}

{
  printf '# Autogenerated by render/hypr.sh\n'
  printf '# Source: %s\n\n' "${src}"
  printf '# Standard theme colors\n'
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    printf '$color%s = %s\n' "$i" "${c[$i]}"
  done
  printf '\n# Hyprland-friendly helpers (no leading '\''#'\'')\n'
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    printf '$color%see = %see\n' "$i" "${c[$i]#\#}"
  done
  printf '\n$background = %s\n' "${bg}"
  printf '$foreground = %s\n' "${fg}"
  printf '$cursor = %s\n\n' "${cursor}"
  emit_borders
} > "${tmp}"

render_commit "${tmp}" "${hash}"
trap - EXIT
