#!/usr/bin/env bash
set -euo pipefail
PALETTE_ARG="${1:-}"
. "$(dirname "$0")/_lib.sh"
# Pack hypr.theme is generation input, not runtime Hyprland configuration or a
# colors override. Always derive native Lua from it.
render_init hypr colors.meta hypr.theme

hash="$(render_input_hash)"
lua_output="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/themes/colors.lua"
render_should_skip "${hash}" && [[ -f "${lua_output}" ]] && exit 0

tmp="$(render_temp)"
trap 'rm -f "${tmp}"' EXIT

mapfile -t palette_values < <(jq -r '.bg, .fg, (.cursor // .fg), (.colors[])' "${PALETTE}")
bg="${palette_values[0]}" fg="${palette_values[1]}" cursor="${palette_values[2]}"
c=("${palette_values[@]:3}")

palette_source="theme:${HYPR_THEME:-unknown}"
[[ -f "${PALETTE}" ]] && palette_source="$(jq -r '.source' "${PALETTE}")"

mode="$(jq -r '.mode // ""' "${PALETTE}")"
source_field="$(jq -r '.source // ""' "${PALETTE}")"

# Border source of truth:
#   theme mode     -> pack's hypr.theme verbatim (no border directives if the pack omits them)
#   wallpaper mode -> derived from palette
emit_borders() {
  if [[ "${mode}" == "theme" && "${source_field}" == theme:* ]]; then
    local pack_hypr="${HOME}/.config/hypr/themes/${source_field#theme:}/hypr.theme"
    [[ -f "${pack_hypr}" ]] || return 0
    awk '
      /^[[:space:]]*(general|group)[[:space:]]*\{/ { in_block=1; block_buf=""; matched=0; print; next }
      in_block && /^[[:space:]]*\}/ { if (matched) print block_buf; print; in_block=0; next }
      in_block {
        if ($0 ~ /^[[:space:]]*col\.(active_border|inactive_border|border_(active|inactive|locked_active|locked_inactive))[[:space:]]*=/) {
          block_buf = block_buf $0 "\n"; matched=1
        }
        next
      }
      { next }
    ' "${pack_hypr}"
  else
    local active_border_color="${c[4]#\#}ff"
    local inactive_border_background="${c[0]#\#}cc"
    local inactive_border_foreground="${c[8]#\#}cc"
    cat <<EOF
general {
    col.active_border = rgba(${active_border_color}) rgba(${active_border_color}) 45deg
    col.inactive_border = rgba(${inactive_border_background}) rgba(${inactive_border_foreground}) 45deg
}

group {
    col.border_active = rgba(${active_border_color}) rgba(${active_border_color}) 45deg
    col.border_inactive = rgba(${inactive_border_background}) rgba(${inactive_border_foreground}) 45deg
    col.border_locked_active = rgba(${active_border_color}) rgba(${active_border_color}) 45deg
    col.border_locked_inactive = rgba(${inactive_border_background}) rgba(${inactive_border_foreground}) 45deg
}
EOF
  fi
}

{
  printf '# Autogenerated by render/hypr.sh\n'
  printf '# Source: %s\n\n' "${palette_source}"
  printf '# Standard theme colors\n'
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    printf '$color%s = %s\n' "$i" "${c[$i]}"
  done
  printf '\n# Hyprland-friendly helpers (no leading '\''#'\'')\n'
  for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    printf '$color%see = %see\n' "$i" "${c[$i]#\#}"
  done
  printf '\n$background = %s\n' "${bg}"
  printf '$foreground = %s\n' "${fg}"
  printf '$cursor = %s\n\n' "${cursor}"
  emit_borders
} > "${tmp}"

render_commit "${tmp}" "${hash}"
"${HYPR_LIB_DIR:-$HOME/.local/lib/hypr}/util/hypr-to-lua.py" --input "${OUT_FILE}" --output "${lua_output}"
trap - EXIT
