#!/usr/bin/env bash
set -euo pipefail
PALETTE_ARG="${1:-}"
. "$(dirname "$0")/_lib.sh"
render_init tmux colors.conf

render_begin

if [[ -n "${PACK_OVERRIDE}" ]]; then
  render_emit_pack_override "${tmp}"
else
  render_read_palette
  cat > "${tmp}" <<EOF
# Generated by render/tmux
set -g status-style "bg=${bg},fg=${fg}"
set -g window-status-current-style "bg=${c[4]},fg=${bg},bold"
set -g window-status-style "bg=${bg},fg=${fg}"
set -g pane-active-border-style "fg=${c[4]}"
set -g pane-border-style "fg=${c[8]}"
set -g message-style "bg=${c[8]},fg=${fg}"
set -g message-command-style "bg=${c[8]},fg=${fg}"
set -g mode-style "bg=${c[4]},fg=${bg}"
EOF
fi

render_commit "${tmp}" "${hash}"
trap - EXIT
