$HOME/.config/dunst/theme.conf

@define-color fg-primary #54433A;
@define-color fg-secondary #739797;

@define-color bg-primary #F1F1F1;
@define-color bg-secondary #E9E1DB;
@define-color bg-tertiary #D9D3CE;

@define-color accent-red #BF0021;
@define-color accent-green #3A684A;
@define-color accent-yellow #A06D00;
@define-color accent-blue #465AA4;
@define-color accent-purple #904180;
@define-color accent-aqua #3D6568;
@define-color accent-orange #BC5C00;

@define-color border-primary #BE79BB;
@define-color border-secondary #739797;

@define-color gray #A98A78;
