$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$ICON_THEME = Fluent-light
$COLOR_SCHEME = prefer-light
$NVIM_SCHEME = melange
$NVIM_VARIANT = light
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false

$CURSOR_THEME = BreezeX-Dark
$CURSOR_SIZE = 28

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(A06D00ff)
    col.inactive_border = rgba(A98A78cc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(A06D00ff)
    col.border_inactive = rgba(A98A78cc)
    col.border_locked_active = rgba(A06D00ff)
    col.border_locked_inactive = rgba(A98A78cc)
}

decoration {
    rounding = 3
    shadow:enabled = false

    blur {
        enabled = yes
        size = 8
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur on, match:namespace waybar
