$HOME/.config/rofi/theme.rasi
* {
    background:            #E9E1DBe6;
    background-alpha:    #E9E1DB59;
    foreground:            #54433Aff;
    border:            #A98A78ff;
    accent:            #7892BDff;
    selected-background:          #739797ff;
    selected-foreground:          #D9D3CEff;
    separator:           #80808080;
    urgent:              #BF0021ff;
    active:              #A06D00ff;
}
