background = "#1c1c1c"
foreground = "#c0c0c0"
cursor-color = "#bdfe58"
cursor-text = "#1c1c1c"
selection-foreground = "#1c1c1c"
selection-background = "#1bfd9c"

colors = [
  "#1c1c1c",
  "#ffb3ba",
  "#baffc9",
  "#ffffba",
  "#7fa1c3",
  "#b2d8d8",
  "#1bfd9c",
  "#c0c0c0",
  "#404040",
  "#dea6a0",
  "#d6efd8",
  "#bedc74",
  "#a1a1a1",
  "#c5c5c5",
  "#bdfe58",
  "#f1f1f1",
]
