# Auto-generated by wal.qutebrowser.sh
# DO NOT EDIT MANUALLY - This file is regenerated on theme change

# Hyprland Integration
hypr_border = 4  # Border radius from Hyprland
color_mode = 0     # Color mode from staterc (0=Theme, 1=Auto, 2=Dark, 3=Light)
border_radius = '4px'

# Color mode names
color_mode_names = {0: 'Theme', 1: 'Auto', 2: 'Dark', 3: 'Light'}
color_mode_name = color_mode_names.get(color_mode, 'Unknown')

# Apply border radius to hints
c.hints.radius = hypr_border

# Note: Border color (c.hints.border) is set by pywal-colors.py

# Apply color mode to webpage preferences
if color_mode == 0:  # Theme mode
    # Use theme colors, respect system preference
    pass
elif color_mode == 1:  # Auto mode
    c.colors.webpage.preferred_color_scheme = 'auto'
    c.colors.webpage.darkmode.enabled = True
elif color_mode == 2:  # Dark mode
    c.colors.webpage.preferred_color_scheme = 'dark'
    c.colors.webpage.darkmode.enabled = True
elif color_mode == 3:  # Light mode
    c.colors.webpage.preferred_color_scheme = 'light'
    c.colors.webpage.darkmode.enabled = False

# Log for debugging
print(f'Hyprland sync: border_radius={hypr_border}px, color_mode={color_mode_name} ({color_mode})')
