$HOME/.config/rofi/theme.rasi
* {
    background:            #0e111a;
    foreground:            #44599b;
    border:            #78C6EB;
    accent:            #114ccf;
    selected-foreground:          #151B25;
    selected-background:          #04ddff;
    separator:           #80808080;
    urgent:              #78C6EB;
    active:              #114ccf;
    separatorcolor:     transparent;
    border-color:       transparent;
}
