$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta
$ICON_THEME = Kanagawa
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = kanagawa
$NVIM_VARIANT = wave
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false

$CURSOR_THEME = MacTahoe-cursors
$CURSOR_SIZE = 30

$FONT = CaskaydiaCove Nerd Font
$BAR_FONT = CaskaydiaCove Nerd Font
$MENU_FONT = CaskaydiaCove Nerd Font
$MONOSPACE_FONT = CaskaydiaCove Nerd Font
$TERMINAL_FONT = CaskaydiaCove Nerd Font
$NOTIFICATION_FONT = CaskaydiaCove Nerd Font Mono

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(C8C093FF)
    col.inactive_border = rgba(363646CC) 
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(C8C093FF) 
    col.border_inactive = rgba(363646CC) 
    col.border_locked_active = rgba(C8C093FF) 
    col.border_locked_inactive = rgba(363646CC) 
}

decoration {
    rounding = 3

    shadow {
        enabled = false
    }

    blur {
        enabled = yes
        size = 4
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
