#!/usr/bin/env bash
# Sourced module; strict mode is owned by the entrypoint.

nerd_font_display_name_from_package() {
  local pkg="$1"
  local display=""

  display="$(printf '%s\n' "${pkg}" | sed -E 's/^(ttf-|otf-)//; s/-(nerd|nerdfonts)$//' | sed 's/-/ /g')"
  display="$(printf '%s\n' "${display}" | awk '{for (i = 1; i <= NF; i++) $i = toupper(substr($i,1,1)) substr($i,2); print}')"
  [[ -n "${display}" ]] || display="${pkg}"
  printf '%s\n' "${display}"
}

nerd_font_metadata_display_name() {
  local description="$1"

  if [[ "${description}" =~ ^Patched[[:space:]]font[[:space:]](.+)[[:space:]]from[[:space:]]nerd[[:space:]]fonts[[:space:]]library$ ]]; then
    printf '%s\n' "${BASH_REMATCH[1]}"
    return 0
  fi

  return 1
}

nerd_font_populate_metadata_labels() {
  local out_map_name="$1"
  shift
  local -a packages=("$@")
  local pkg=""
  local description=""
  local label=""

  local -n metadata_label_map_ref="${out_map_name}"

  [[ "${#packages[@]}" -gt 0 ]] || return 0

  while IFS=$'\t' read -r pkg description; do
    [[ -n "${pkg}" ]] || continue
    label="$(nerd_font_metadata_display_name "${description}" || true)"
    [[ -n "${label}" ]] || continue
    # shellcheck disable=SC2034 # Nameref output assigned for the caller.
    metadata_label_map_ref["${pkg}"]="${label}"
  done < <(
    pacman -Si -- "${packages[@]}" 2>/dev/null |
      awk '
        /^Name[[:space:]]*:/ {
          sub(/^[^:]+:[[:space:]]*/, "", $0)
          name=$0
          next
        }
        /^Description[[:space:]]*:/ {
          sub(/^[^:]+:[[:space:]]*/, "", $0)
          if (name != "") printf "%s\t%s\n", name, $0
          name=""
        }
      '
  )
}

nerd_font_menu_build() {
  local mode="$1"
  local out_labels_name="$2"
  local out_map_name="$3"
  local package_list=""
  local pkg=""
  local label=""
  local -a packages=()
  local -A seen_labels=()
  local -A metadata_labels=()

  local -n font_menu_labels_ref="${out_labels_name}"
  local -n font_menu_package_map_ref="${out_map_name}"
  font_menu_labels_ref=()
  font_menu_package_map_ref=()

  case "${mode}" in
    installable)
      package_list="$(hyprshell fonts/font-nerd-install.sh --list-installable 2>/dev/null || true)"
      ;;
    installed)
      package_list="$(hyprshell fonts/font-nerd-remove.sh --list-installed 2>/dev/null || true)"
      ;;
    unused)
      package_list="$(hyprshell fonts/font-nerd-remove.sh --list-unused 2>/dev/null || true)"
      ;;
    *)
      return 1
      ;;
  esac

  mapfile -t packages < <(printf '%s\n' "${package_list}" | sed '/^$/d')
  nerd_font_populate_metadata_labels metadata_labels "${packages[@]}"

  while IFS= read -r pkg; do
    [[ -n "${pkg}" ]] || continue
    label="${metadata_labels["${pkg}"]:-}"
    [[ -n "${label}" ]] || label="$(nerd_font_display_name_from_package "${pkg}")"
    if [[ -n "${seen_labels["${label}"]:-}" ]]; then
      label="${label} [${pkg}]"
    fi
    seen_labels["${label}"]=1
    font_menu_labels_ref+=("${label}")
    # shellcheck disable=SC2034 # Associative-array output assigned for the caller.
    font_menu_package_map_ref["${label}"]="${pkg}"
  done <<<"${package_list}"
}

show_font_menu() {
  local font_list=""
  local current_font=""
  local font=""
  local menu_exit=0

  font_list="$(hyprshell fonts/font-list.sh)"
  current_font="$(hyprshell fonts/font-get.sh mono 2>/dev/null || true)"
  font="$(menu "Select Font" "Theme Default\n${font_list}" --select "${current_font}" --nav copy)"
  menu_exit=$?

  if [[ -z "${font}" || "${font}" == "CNCLD" ]]; then
    menu_exit_or_show style
    return 0
  fi

  if ((menu_exit == MENU_EXIT_COPY)); then
    [[ "${font}" == "Theme Default" ]] && return 0
    printf '%s' "${font}" | wl-copy
    send_ephemeral_notif "font-copy" -a "Font" -t 2000 "Copied" "${font}"
    return 0
  fi

  if [[ "${font}" == "Theme Default" ]]; then
    printf '%s\n' '-- User font overrides are generated by hyprshell fonts/font-set.sh.' \
      > "${HYPR_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr}/userfonts.lua"
    hyprshell fonts/font-apply.sh >/dev/null 2>&1 &
  else
    hyprshell fonts/font-set.sh "${font}" >/dev/null 2>&1 &
  fi
}

show_setup_power_profile_menu() {
  local profile=""

  profile="$(menu "Power Profile" "$(hyprshell system/powerprofiles.sh)" --select "$(busctl --system get-property org.freedesktop.UPower.PowerProfiles /org/freedesktop/UPower/PowerProfiles org.freedesktop.UPower.PowerProfiles ActiveProfile 2>/dev/null | awk -F'"' '{print $2}')")"
  if [[ -z "${profile}" || "${profile}" == "CNCLD" ]]; then
    menu_exit_or_show setup
    return 0
  fi

  hyprshell system/powerprofiles.sh --set "${profile}"
}

show_install_font_menu() {
  local selection=""
  local label=""
  local title=""
  local -a font_labels=()
  local -A font_packages=()
  local -a packages=()

  nerd_font_menu_build installable font_labels font_packages
  if [[ "${#font_labels[@]}" -gt 0 ]]; then
    selection="$(menu "Install Font" "$(printf '%s\n' "${font_labels[@]}")" --nav multi)"
  else
    selection="$(menu "Install Font" "No installable Nerd Fonts")"
  fi

  case "${selection}" in
    "No installable Nerd Fonts" | "" | "CNCLD")
      menu_exit_or_show install
      return 0
      ;;
  esac

  while IFS= read -r label; do
    [[ -n "${label}" ]] || continue
    [[ -n "${font_packages["${label}"]:-}" ]] || continue
    packages+=("${font_packages["${label}"]}")
    title+="${label}, "
  done <<<"${selection}"

  if [[ "${#packages[@]}" -eq 0 ]]; then
    show_install_font_menu
    return 0
  fi

  if [[ "${#packages[@]}" -gt 1 ]]; then
    title="${#packages[@]} Nerd Fonts"
  else
    title="${title%, }"
  fi

  present_terminal --hypr-profile dialog --app-id org.font.Install --title "Install ${title}" -- hyprshell fonts/font-nerd-install.sh --packages "${packages[@]}"
}

show_remove_font_menu() {
  local mode="${1:-all}"
  local unused_option="  Unused"
  local prompt="Remove Font"
  local empty_label="No installed Nerd Fonts"
  local selection=""
  local package=""
  local -a font_labels=()
  local -A font_packages=()

  case "${mode}" in
    unused)
      prompt="Remove Unused Font"
      empty_label="No unused Nerd Fonts"
      nerd_font_menu_build unused font_labels font_packages
      ;;
    *)
      nerd_font_menu_build installed font_labels font_packages
      ;;
  esac

  if [[ "${#font_labels[@]}" -gt 0 ]]; then
    if [[ "${mode}" == "unused" ]]; then
      selection="$(menu "${prompt}" "$(printf '%s\n' "${font_labels[@]}")")"
    else
      selection="$(menu "${prompt}" "${unused_option}\n$(printf '%s\n' "${font_labels[@]}")")"
    fi
  else
    if [[ "${mode}" == "unused" ]]; then
      selection="$(menu "${prompt}" "${empty_label}")"
    else
      selection="$(menu "${prompt}" "${unused_option}\n${empty_label}" --select "${unused_option}")"
    fi
  fi

  case "${selection}" in
    "${unused_option}")
      show_remove_font_menu unused
      ;;
    "${empty_label}" | "" | "CNCLD")
      menu_exit_or_show remove
      ;;
    *)
      package="${font_packages["${selection}"]:-}"
      [[ -n "${package}" ]] || {
        show_remove_font_menu
        return 0
      }
      present_terminal --hypr-profile dialog --app-id org.font.Remove --title "Remove ${selection}" -- hyprshell fonts/font-nerd-remove.sh --packages "${package}"
      ;;
  esac
}

show_media_genre_menu() {
  local empty_label="Music library is empty"
  local library=""
  local albums=""
  local selection=""

  library="$(hyprshell media/music_library_config 2>/dev/null | tail -n1)"
  # tag_genres reads one directory without descending, so only offer the
  # directories that actually hold tracks
  if [[ -n "${library}" && -d "${library}" ]]; then
    albums="$(
      find "${library}" -mindepth 1 -type f \
        \( -iname '*.mp3' -o -iname '*.opus' -o -iname '*.flac' \) \
        -printf '%h\n' 2>/dev/null | sed "s|^${library}/\?||" | sed '/^$/d' | sort -u
    )"
  fi

  if [[ -n "${albums}" ]]; then
    selection="$(menu "Album" "${albums}")"
  else
    selection="$(menu "Album" "${empty_label}")"
  fi

  case "${selection}" in
    "${empty_label}" | "" | "CNCLD")
      menu_exit_or_show media
      ;;
    *)
      present_terminal hyprshell media/tag_genres "${library}/${selection}"
      ;;
  esac
}

show_session_snapshot_menu() {
  local mode="${1:-restore}"
  local empty_label="No saved sessions"
  local prompt="Restore Session"
  local names=""
  local selection=""

  [[ "${mode}" == "delete" ]] && prompt="Delete Session"

  names="$(hyprshell session/snapshot.py list 2>/dev/null)"
  [[ "${names}" == "no saved sessions" ]] && names=""

  if [[ -n "${names}" ]]; then
    selection="$(menu "${prompt}" "${names}")"
  else
    selection="$(menu "${prompt}" "${empty_label}")"
  fi

  case "${selection}" in
    "${empty_label}" | "" | "CNCLD")
      menu_exit_or_show system_session
      ;;
    *)
      present_terminal hyprshell session/snapshot.py "${mode}" "${selection}"
      ;;
  esac
}

show_search_all_menu() {
  menu_show_search main
}

menu_run_action_dynamic() {
  local action_id="$1"

  case "${action_id}" in
    search_all)
      show_search_all_menu
      return 0
      ;;
    style_font)
      show_font_menu
      ;;
    setup_power_profile)
      show_setup_power_profile_menu
      ;;
    install_font)
      show_install_font_menu
      ;;
    remove_font)
      show_remove_font_menu
      ;;
    media_genres)
      show_media_genre_menu
      ;;
    system_session_restore)
      show_session_snapshot_menu restore
      ;;
    system_session_delete)
      show_session_snapshot_menu delete
      ;;
    *)
      return 1
      ;;
  esac

  return 0
}

menu_register_action_handler menu_run_action_dynamic
