background = "#faf4ed"
foreground = "#575279"
cursor-color = "#cecacd"
cursor-text = "#575279"
selection-foreground = "#575279"
selection-background = "#dfdad9"

colors = [
  "#f2e9e1",
  "#b4637a",
  "#286983",
  "#ea9d34",
  "#56949f",
  "#907aa9",
  "#d7827e",
  "#575279",
  "#9893a5",
  "#b4637a",
  "#286983",
  "#ea9d34",
  "#56949f",
  "#907aa9",
  "#d7827e",
  "#575279",
]
