$HOME/.config/alacritty/theme.toml

[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"

[colors.cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.selection]
text = "#100F0F"
background = "#CECDC3"

[colors.search.matches]
foreground = "#100F0F"
background = "#D0A215"

[colors.footer_bar]
foreground = "#100F0F"
background = "#CECDC3"

[colors.normal]
black = "#100F0F"
red = "#AF3029"
green = "#66800B"
yellow = "#AD8301"
blue = "#205EA6"
magenta = "#A02F6F"
cyan = "#24837B"
white = "#6F6E69"

[colors.bright]
black = "#6F6E69"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#100F0F"
