$HOME/.config/kitty/theme.conf

background #FFFCF0
foreground #100F0F
selection_foreground #100F0F
selection_background #CECDC3
cursor #100F0F
cursor_text_color #FFFCF0

url_color #205EA6

active_border_color #205EA6
inactive_border_color #6F6E69
bell_border_color #AF3029

active_tab_background #205EA6
active_tab_foreground #FFFCF0
inactive_tab_background #CECDC3
inactive_tab_foreground #100F0F
tab_bar_background #FFFCF0

color0 #100F0F
color1 #AF3029
color2 #66800B
color3 #AD8301
color4 #205EA6
color5 #A02F6F
color6 #24837B
color7 #6F6E69
color8 #6F6E69
color9 #D14D41
color10 #879A39
color11 #D0A215
color12 #4385BE
color13 #CE5D97
color14 #3AA99F
color15 #100F0F
