$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-black
$COLOR_SCHEME = prefer-dark
$NVIM_SCHEME = ashen
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$CURSOR_THEME = BreezeX-Dark
$CURSOR_SIZE = 30
$FONT = Agave Nerd Font
$BAR_FONT = Agave Nerd Font
$MENU_FONT = Agave Nerd Font
$MONOSPACE_FONT = Agave Nerd Font
$NOTIFICATION_FONT = Agave Nerd Font Mono

general {
    col.active_border = rgba(798186ee) 
    col.inactive_border = rgb(1e1e1e)
    gaps_in = 4
    gaps_out = 8
    border_size = 2
}

group {
    col.border_active = rgba(798186ee) 
    col.border_inactive = rgb(101315)

    groupbar {
        col.active = rgba(79818688)
        col.inactive = rgba(101315aa)
        text_color = rgb(101315)
        text_color_inactive = rgba(798186aa)
    }
}

decoration {
    rounding = 4
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000052)
    }
}
