background = "#101315"
foreground = "#cacccc"
cursor-color = "#cacccc"
cursor-text = "#101315"
selection-foreground = "#101315"
selection-background = "#798186"

colors = [
  "#101315",
  "#565d60",
  "#9fa5a9",
  "#d9dbdc",
  "#798186",
  "#aeaeae",
  "#707070",
  "#cbc2be",
  "#4b4e55",
  "#de6145",
  "#343d41",
  "#c9c2b4",
  "#5d6367",
  "#9a9a9a",
  "#707070",
  "#a5aeb4",
]
