$HOME/.config/rofi/theme.rasi
* {
    background:            #131311B3;
    background-alpha:      #13131159;
    foreground:            #FFFFCCE6;
    border:                #5E4533E6;
    accent:                #525229E6;
    selected-background:   #F0CBAA80;
    selected-foreground:   #523C29E6;
    separator:             #80808080;
    urgent:                #5E4533E6;
    active:                #E6E69AE6;
}
