$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Beauty-yellow-dark
$COLOR_SCHEME = prefer-dark
$CURSOR_THEME = Sweet-cursors
$CURSOR_SIZE = 30

$NVIM_SCHEME = cyberdream
$NVIM_VARIANT = default
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false
$FONT = RecMonoCasual Nerd Font
$BAR_FONT = RecMonoCasual Nerd Font
$MENU_FONT = RecMonoCasual Nerd Font
$MONOSPACE_FONT = RecMonoCasual Nerd Font
$TERMINAL_FONT = RecMonoCasual Nerd Font
$NOTIFICATION_FONT = RecMonoCasual Nerd Font Mono

general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(c74dedff)
    col.inactive_border = rgba(00c1e4cc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(c74dedff)
    col.border_inactive = rgba(00c1e4cc)
    col.border_locked_active = rgba(c74dedff)
    col.border_locked_inactive = rgba(00c1e4cc)
}

decoration {
    rounding = 3

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = false
    }
}
