background = "#161925"
foreground = "#c3c7c8"
cursor-color = "#c3c7c8"
cursor-text = "#161925"
selection-foreground = "#161925"
selection-background = "#bd93f9"

colors = [
  "#697388",
  "#ed254e",
  "#71f79f",
  "#f9dc5c",
  "#7cb7ff",
  "#c74ded",
  "#00c1e4",
  "#dcdfe4",
  "#697388",
  "#ed254e",
  "#71f79f",
  "#f9dc5c",
  "#7cb7ff",
  "#c74ded",
  "#00c1e4",
  "#dcdfe4",
]
