$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Fluent-grey-dark
$COLOR_SCHEME = prefer-dark

$NVIM_SCHEME = zenbones
$NVIM_VARIANT = default
$NVIM_BACKGROUND = dark
$NVIM_TRANSPARENCY = false

$CURSOR_THEME = Vimix-cursors
$CURSOR_SIZE = 30
$FONT = iMWritingMono Nerd Font
$BAR_FONT = iMWritingMono Nerd Font
$MENU_FONT = iMWritingMono Nerd Font
$MONOSPACE_FONT = iMWritingMono Nerd Font
$TERMINAL_FONT = iMWritingMono Nerd Font
$NOTIFICATION_FONT = iMWritingMono Nerd Font Mono

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(888F94ff)
    col.inactive_border = rgba(352F2Dcc)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(888F94ff)
    col.border_inactive = rgba(352F2Dcc)
    col.border_locked_active = rgba(888F94ff)
    col.border_locked_inactive = rgba(352F2Dcc)
}

decoration {
    rounding = 0

    shadow {
        enabled = yes
        offset = 4 4
        range = 0
        render_power = 4
        ignore_window = yes
        color = 0xffC4CACF
    }
    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
