$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

# vim:ft=kitty
## name: zenbones_dark
## author: Michael Chris Lopez
## license: MIT
## upstream: https://github.com/mcchrish/zenbones.nvim/raw/main/extras/kitty/zenbones_dark.conf
## blurb: A contrast-based colorscheme.

foreground                      #B4BDC3
background                      #1C1917
selection_foreground            #B4BDC3
selection_background            #3D4042

# Cursor colors
cursor                          #C4CACF
cursor_text_color               #1C1917

# URL underline color when hovering with mouse
# kitty window border colors
# OS Window titlebar colors

# Tab bar colors
active_tab_foreground   #65435E
inactive_tab_foreground #352F2D
tab_bar_background      #1C1917

# Colors for marks (marked text in the terminal)

# The basic 16 colors

# black
color0 #1C1917
color8 #403833

# red
color1 #DE6E7C
color9 #E8838F

# green
color2  #66A5AD
color10 #65B8C1

# yellow
color3  #B279A7
color11 #CF86C1

# blue
color4  #888F94
color12 #888F94

# magenta
color5  #B279A7
color13 #CF86C1

# cyan
color6  #66A5AD
color14 #65B8C1

# white
color7  #D9D9D9
color15 #D9D9D9
