-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x07D8",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
hl.workspace_rule({
  workspace = "1",
  monitor = "desc:BOE 0x07D8",
  default = true,
  persistent = true,
})
hl.workspace_rule({
  workspace = "2",
  monitor = "desc:BOE 0x07D8",
})
hl.workspace_rule({
  workspace = "3",
  monitor = "desc:BOE 0x07D8",
})
hl.workspace_rule({
  workspace = "4",
  monitor = "desc:BOE 0x07D8",
})
hl.workspace_rule({
  workspace = "5",
  monitor = "desc:BOE 0x07D8",
})
