-- Generated by the Quickshell language module.
-- Use the bar popup or hyprshell util/keyboard-layout to edit it.
hl.config({
    input = {
        kb_layout = "us,fr",
        kb_variant = ",",
        kb_options = "",
    },
})
