-- Generated by nwg-displays on 2026-05-22 at 16:06:57. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
