$HOME/.config/rofi/theme.rasi
* {
    background:            #14221ce6;
    background-alpha:    #14221c59;
    foreground:            #bdebb2ff;
    border:            #5AA65Fff;
    accent:            #fabd2fff;
    selected-background:          #5AA65Fff;
    selected-foreground:          #282828ff;
    separator:           #80808080;
    urgent:              #f07178ff;
    active:              #c3e88dff;
}