$HOME/.config/dunst/theme.conf

@define-color fg-primary #4d2e1a;
@define-color fg-secondary #4d2e1a;
@define-color bg-primary #dfd2c4;
@define-color bg-secondary #dfd2c4;
@define-color bg-tertiary #dfd2c4;
@define-color accent-red #a4373c;
@define-color accent-green #a46d2d;
@define-color accent-yellow #a8611f;
@define-color accent-blue #a32f1a;
@define-color accent-purple #9c3521;
@define-color accent-aqua #755833;
@define-color accent-orange #e48e3e;
@define-color border-primary #a32f1a;
@define-color border-secondary #9f8253;
@define-color gray #9f8253;
