$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-red
$COLOR_SCHEME = prefer-light
$NVIM_SCHEME = token
# $NVIM_VARIANT = classic
# $NVIM_BACKGROUND = light
# $NVIM_TRANSPARENCY = true
$CURSOR_THEME = OpenZone_Fire
$CURSOR_SIZE = 30
$FONT = M+1Code Nerd Font
$BAR_FONT = M+1Code Nerd Font
$MENU_FONT = M+1Code Nerd Font
$MONOSPACE_FONT = M+1Code Nerd Font
$TERMINAL_FONT = M+1Code Nerd Font
$NOTIFICATION_FONT = M+1Code Nerd Font Mono

general {
    col.active_border = rgb(a32f1a) rgba(13131dee) 45deg
    border_size = 3
    gaps_in = 4
    gaps_out = 9
}

group {
    col.border_active = rgb(a32f1a) rgba(13131dee) 45deg
}

decoration {
    rounding = 5
    active_opacity = 0.9
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0
    blur {
        enabled = yes
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    shadow {
      enabled = yes
      render_power = 4
      range = 5
      color = rgba(00000052)
    }
}
