$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-red
$COLOR_SCHEME = prefer-light
$NVIM_BACKGROUND = light
$NVIM_TRANSPARENCY = false

$CURSOR_THEME = GoogleDot-Blue

general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(F7B500ff)
    col.inactive_border = rgba(D8CCB8d9)
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(F7B500ff)
    col.border_inactive = rgba(D8CCB8d9)
    col.border_locked_active = rgba(F7B500ff)
    col.border_locked_inactive = rgba(D8CCB8d9)
}

decoration {
    rounding = 4
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur on, match:namespace waybar
