background = "#EEE2D0"
foreground = "#3C5478"
cursor-color = "#3C5478"
cursor-text = "#EEE2D0"
selection-foreground = "#F4EEE3"
selection-background = "#F7B500"

colors = [
  "#3C5478",
  "#CC2C24",
  "#6F9A84",
  "#C49800",
  "#376B8C",
  "#B06F78",
  "#6F9996",
  "#D8CCB8",
  "#6B7B8C",
  "#E04038",
  "#87B29C",
  "#F7B500",
  "#4A88B0",
  "#CC8A92",
  "#87B1AE",
  "#F4EEE3",
]
