background = "#0C0B16"
foreground = "#eceffd"
cursor-color = "#fdcd5e"
cursor-text = "#0C0B16"
selection-foreground = "#0C0B16"
selection-background = "#e9114f"

colors = [
  "#03063c",
  "#c60049",
  "#abf157",
  "#fdcd5e",
  "#525fb8",
  "#976f81",
  "#968662",
  "#eceffc",
  "#6c5a30",
  "#d94a8a",
  "#daffa8",
  "#fee6a8",
  "#b1bdf9",
  "#fda4cc",
  "#a4bc86",
  "#f6ffec",
]
