# --- pane-border configuration ------------------------------------------------
setw -g pane-border-status top
setw -g pane-border-format "#[italics]#($HOME/.config/tmux/scripts/tmux-pane-title #{pane_current_command})#[default]"

set -g pane-border-indicators colour
setw -g pane-border-lines single

setw -g window-status-activity-style none
setw -g window-status-separator ""

# -- popup style ---------------------------------------------------------------
set -g popup-style "bg=default"
set -g popup-border-style "fg=default,bg=default"
set -g popup-border-lines "padded"

# -- status layout -------------------------------------------------------------
set -g status-left "#{tmux_mode_indicator}"
set -g status-left-length 500

setw -g window-status-current-format "#[italics,bold]#[fg=#{@theme_accent},bg=terminal]  #I:#W#{E:@sup_window_panes}#[default]#{?window_bell_flag,#[fg=#{@theme_red}] 󰂞#[default],}#{?window_zoomed_flag,#[fg=#{@theme_red}]#{E:@sup_pane_index}#[default],}"
setw -g window-status-format "  #I:#W#{E:@sup_window_panes}#{?window_bell_flag,#[fg=#{@theme_red}] 󰂞#[default],}#{?window_zoomed_flag,#[fg=#{@theme_red}]#{E:@sup_pane_index}#[default],}"

set -g status-right "#{?#{!=:#{battery_percentage},0},#[nobold,fg=#{battery_color_fg}]#{battery_icon} #{battery_percentage}#[default],} #[fg=#{@theme_gray}]#($XDG_CONFIG_HOME/tmux/scripts/tmux-player)#[default]#{?#{!=:#{pomodoro_status},},#[bold]#{pomodoro_status}#[default] #[fg=#{@theme_accent}]⋮#[default],} #[bold]#{cpu_fg_color}#{cpu_percentage}#[default] #[bold]#{ram_fg_color}#{ram_icon}#[default] "
set -g status-right-length 200
