# --- pane-border configuration ------------------------------------------------
setw -g pane-border-status top
setw -g pane-border-format "#[italics]#(/home/rifle/.config/tmux/scripts/tmux-pane-title #{pane_current_command})#[default]"

set -g pane-border-indicators colour
setw -g pane-border-lines single

setw -g window-status-activity-style none
setw -g window-status-separator ""

# -- popup style ---------------------------------------------------------------
set -g popup-style "bg=default"
set -g popup-border-style "fg=default,bg=default"
set -g popup-border-lines "padded"

# -- status layout -------------------------------------------------------------
set -g status-left "#[bold]#[fg=default,bg=#{@theme_gray}]#{tmux_mode_indicator}#[default]"
set -g status-left-length 500

setw -g window-status-current-format "#[italics,bold]#[fg=#{@theme_accent},bg=terminal]  #I:#W#(echo #{window_panes} | sed 's/0/⁰/g;s/1/¹/g;s/2/²/g;s/3/³/g;s/4/⁴/g;s/5/⁵/g;s/6/⁶/g;s/7/⁷/g;s/8/⁸/g;s/9/⁹/g')#[default]#{?window_bell_flag,#[fg=#{@theme_red}] 󰂞#[default],}#{?window_zoomed_flag,#[fg=#{@theme_red}]#(/home/rifle/.config/tmux/scripts/tmux-pane-numbers\ #P)#[default],}"
setw -g window-status-format "  #I:#W#(echo #{window_panes} | sed 's/0/⁰/g;s/1/¹/g;s/2/²/g;s/3/³/g;s/4/⁴/g;s/5/⁵/g;s/6/⁶/g;s/7/⁷/g;s/8/⁸/g;s/9/⁹/g')#{?window_bell_flag,#[fg=#{@theme_red}] 󰂞#[default],}#{?window_zoomed_flag,#[fg=#{@theme_red}]#(/home/rifle/.config/tmux/scripts/tmux-pane-numbers\ #P)#[default],}"

set -g status-right "#{?#{!=:#{battery_percentage},0},#[nobold,fg=#{battery_color_fg}]#{battery_icon} #{battery_percentage}#[default],} #[fg=#{@theme_gray}]#($XDG_CONFIG_HOME/tmux/scripts/tmux-player)#[default] #[bold]#{pomodoro_status}#[default] #[fg=#{@theme_accent}]⋮#[default] #[bold]#{cpu_fg_color}#{cpu_percentage}#[default] #[bold]#{ram_fg_color}#{ram_icon}#[default] "
set -g status-right-length 200
