$HOME/.config/rofi/theme.rasi
* {
    background:            #E5D8C6e6;
    background-alpha:    #E5D8C659;
    foreground:            #3D3632ff;
    border:            #C4B19Eff;
    accent:            #AD8A3Eff;
    selected-background:          #AD8A3Eff;
    selected-foreground:          #3D3632ff;
    separator:           #80808080;
    urgent:              #B5503Cff;
    active:              #5B8755ff;
}
