#!/usr/bin/env bash

scrDir="$(dirname "$(realpath "$0")")"
# shellcheck disable=SC1091
source "${LIB_DIR:-$HOME/.local/lib}/hypr/globalcontrol.sh"

focusmode_state_file="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}/focusmode.conf"
gamemode_state_file="${HYPR_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/hypr}/gamemode.conf"

write_focusmode_state() {
  mkdir -p "$(dirname "${focusmode_state_file}")"
  cat >"${focusmode_state_file}" <<'EOF'
# Generated by focusmode.sh
animations:enabled = 0
decoration:shadow:enabled = 0
decoration:blur:xray = 1
decoration:blur:enabled = 0
general:gaps_in = 3
general:gaps_out = 6
general:border_size = 2
decoration:rounding = 4
decoration:active_opacity = 1
decoration:inactive_opacity = 1
decoration:fullscreen_opacity = 1
layerrule = noanim,waybar
layerrule = noanim,notifications
layerrule = noanim,swww-daemon
layerrule = noanim,rofi
windowrule = opaque,class:(.*)
EOF
}

disable_focusmode_state() {
  rm -f "${focusmode_state_file}"
}

focusmode_enabled() {
  [[ -f "${focusmode_state_file}" ]] || [[ "$(state_get HYPR_FOCUSMODE 0)" == "1" ]]
}

if focusmode_enabled; then
  disable_focusmode_state
  state_set "HYPR_FOCUSMODE" "0" "staterc"
else
  write_focusmode_state
  rm -f "${gamemode_state_file}"
  state_set "HYPR_FOCUSMODE" "1" "staterc"
  state_set "HYPR_GAMEMODE" "0" "staterc"
fi

hyprctl reload config-only -q
