background = "#f7ecec"
foreground = "#2e2820"
cursor = "#2e2820"

colors = [
  "#2e2820",
  "#df7845",
  "#4e776b",
  "#b4670d",
  "#5085a0",
  "#9a6a9a",
  "#6696ae",
  "#d6caca",
  "#797979",
  "#ff8c5a",
  "#7f8d6a",
  "#db8d34",
  "#7fa1b5",
  "#c28aa8",
  "#9cb6c0",
  "#fff7f7",
]
