$HOME/.config/rofi/theme.rasi
* {
    background:            #262335e6;
    foreground:            #ff7edbff;
    border:                #f97e72ff;
    accent:                #72f1b8ff;
    selected-background:   #03edf9ff;
    selected-foreground:   #495495ff;
    separator:             #80808080;
    urgent:                #f97e72ff;
    active:                #72f1b8ff;
    separatorcolor:     transparent;
    border-color:       transparent;
}
