"""Render a profile into the generated Hyprland monitor config."""
from __future__ import annotations

import os

from . import hypr

HEADER = "-- Generated by hyprmoncfg"
CONF_HEADER = "# Generated by hyprmoncfg"
TARGET = os.path.expanduser(
    os.environ.get("HYPRMONCFG_MONITORS_CONF", "~/.config/hypr/hyprmoncfg-monitors.lua")
)


def _selector(output: dict) -> str:
    """Match on description so a display survives being moved to another port."""
    description = (output.get("description") or "").strip()
    return f"desc:{description}" if description else output.get("name", "")


def _lua_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return '"%s"' % str(value).replace('"', '\\"')


def _fields(output: dict) -> list[tuple[str, object]]:
    if not output.get("enabled", True):
        return [("output", _selector(output)), ("disabled", True)]

    mode = str(output.get("mode", ""))
    fields: list[tuple[str, object]] = [
        ("output", _selector(output)),
        # Hyprland takes the mode without the Hz suffix the profile stores.
        ("mode", mode[:-2] if mode.endswith("Hz") else mode),
        ("position", f"{int(output.get('x', 0))}x{int(output.get('y', 0))}"),
        ("scale", output.get("scale", 1)),
    ]
    if output.get("transform"):
        fields.append(("transform", int(output["transform"])))
    if output.get("mirror_of"):
        fields.append(("mirror", output["mirror_of"]))
    if int(output.get("bitdepth", 8)) == 10:
        fields.append(("bitdepth", 10))
    if str(output.get("cm", "srgb")) not in ("", "srgb"):
        fields.append(("cm", output["cm"]))
    for key in ("sdr_brightness", "sdr_saturation"):
        if output.get(key) not in (None, 1):
            fields.append((key, output[key]))
    for key in ("sdr_min_luminance", "sdr_max_luminance"):
        if output.get(key) is not None:
            fields.append((key, output[key]))
    return fields


def to_lua(profile: dict) -> str:
    blocks = []
    for output in profile.get("outputs", []):
        body = "\n".join(f"  {k} = {_lua_value(v)}," for k, v in _fields(output))
        blocks.append("hl.monitor({\n%s\n})" % body)
    return HEADER + "\n\n" + "\n".join(blocks) + "\n"


def to_conf(profile: dict) -> str:
    blocks = []
    for output in profile.get("outputs", []):
        body = "\n".join(
            "  %s = %s" % (k, "true" if v is True else "false" if v is False else v)
            for k, v in _fields(output)
        )
        blocks.append("monitorv2 {\n%s\n}" % body)
    return CONF_HEADER + "\n\n" + "\n".join(blocks) + "\n"


def write(text: str, path: str = TARGET) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.replace(tmp, path)


def apply(profile: dict, reload: bool = True) -> None:
    """Write the generated config and make Hyprland pick it up."""
    write(to_lua(profile))
    if reload:
        hypr.reload()
