[env]
TERM = "xterm-256color"

[general]
import = [
  "./theme.toml"
]

[terminal]
[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[font]
size = 14
[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
[font.offset]
x = 0
y = 4

[mouse]
hide_when_typing = true

[window]
decorations = "None"
opacity = 1
blur = false
dynamic_padding = true
[window.padding]
x = 10
y = 4
