[colors.primary]
background = "#faf9f5"
foreground = "#4d2e1a"

[colors.cursor]
text = "#faf9f5"
cursor = "#323128"

[colors.selection]
text = "#4d2e1a"
background = "#a32f1a"

[colors.normal]
black = "#dfd2c4"
red = "#a4373c"
green = "#a46d2d"
yellow = "#a8611f"
blue = "#a32f1a"
magenta = "#9c3521"
cyan = "#755833"
white = "#080503"

[colors.bright]
black = "#9f8253"
red = "#d2656a"
green = "#d89b55"
yellow = "#e48e3e"
blue = "#e84d31"
magenta = "#de553a"
cyan = "#b8884c"
white = "#4d2e1a"
