$HOME/.config/hypr/themes/theme.meta|> $HOME/.config/hypr/themes/colors.meta

$ICON_THEME = Tela-red
$COLOR_SCHEME = prefer-light

$NVIM_SCHEME = token
# $NVIM_VARIANT = classic
# $NVIM_BACKGROUND = light
# $NVIM_TRANSPARENCY = true

$CURSOR_THEME = OpenZone_Fire
$CURSOR_SIZE = 30

$FONT = IosevkaTerm Nerd Font
$BAR_FONT = IosevkaTerm Nerd Font
$MENU_FONT = IosevkaTerm Nerd Font
$MONOSPACE_FONT = IosevkaTerm Nerd Font
$TERMINAL_FONT = IosevkaTerm Nerd Font
$NOTIFICATION_FONT = IosevkaTerm Nerd Font Mono

general {
    col.active_border = rgb(e84d31)
    col.inactive_border = rgba(dddcd6ee)
    border_size = 3
    gaps_in = 4
    gaps_out = 9
}

group {
    col.border_active = rgb(a32f1a)
    col.inactive_border = rgba(13131dee)
}

decoration {
    rounding = 3
    active_opacity = 0.9
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0
    blur {
        enabled = yes
        size = 4
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    shadow {
      enabled = yes
      render_power = 4
      range = 5
      color = rgba(00000052)
    }
}
