$HOME/.config/kitty/theme.conf

background #faf9f5
foreground #4d2e1a
cursor #4d2e1a
cursor_text_color #dfd2c4
selection_foreground #4d2e1a
selection_background #a32f1a

active_tab_foreground #a32f1a
inactive_tab_foreground #4d2e1a
tab_bar_background #dddcd6


color0 #dfd2c4
color1 #a4373c
color2 #a46d2d
color3 #a8611f
color4 #a32f1a
color5 #9c3521
color6 #755833
color7 #080503
color8 #9f8253
color9 #d2656a
color10 #d89b55
color11 #e48e3e
color12 #e84d31
color13 #de553a
color14 #b8884c
color15 #4d2e1a
