#!/usr/bin/env sh

sticker="$(rmpc sticker get "$FILE" playCount | jq -r '.value')"
if [ -z "$sticker" ]; then
  sticker=0
fi
rmpc sticker set "$FILE" playCount "$((sticker + 1))"
"$(dirname "$0")/notify"
