#!/usr/bin/env sh

tmp_dir=/tmp/rmpc
mkdir -p "$tmp_dir"
art="$tmp_dir/notification_cover"
rmpc albumart --output "$art" || art="$tmp_dir/default_album_art.jpg"
notify-send -i "$art" "$TITLE" "$ARTIST"
