# Ported from mahaveergurjar/Hyprlock-Dots layout4.conf
$mpris_art = $MPRIS_IMAGE
$artfile = $MPRIS_BLURRED
$album = $HOME/.local/lib/hypr/session/hyprlock.sh --mpris

background {
    monitor =
    path = $BACKGROUND_PATH
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.7172
    vibrancy = 0.1696
    vibrancy_darkness = 0
}
$fn_splash=echo "$($album || hyprctl splash )"

label {
    monitor =
    text = Hi $USER
    font_size = 35
    font_family = $font
    position = 0, 260
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.30
    dots_center = true
    dots_rounding = -1
    outer_color = rgba($tone.c5.72.135.r, $tone.c5.72.135.g, $tone.c5.72.135.b, 0.60)
    inner_color = rgba($tone.c4.59.137.r, $tone.c4.59.137.g, $tone.c4.59.137.b, 0.60)
    font_color = rgba($fg.r, $fg.g, $fg.b, 0.90)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <span size="$ph.175.12.d0f1a715"><i>Input Password...</i></span>
    hide_input = false
    rounding = -1
    check_color = rgba($accent1_2)
    fail_color = rgba($tone.c1.55.204.r, $tone.c1.55.204.g, $tone.c1.55.204.b, 0.60)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = 1
    numlock_color = 1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = true
    position = 0, -350
    halign = center
    valign = center
    font_family = $font
}

label {
    monitor = 
    text = cmd[update:1000] $fn_splash
    font_family = $font, Font Awesome 25 Free Solid
    position = 0, 330
    halign = center
    valign = bottom
}

image {
    monitor = 
    path = $mpris_art
    size = 300
    rounding = $rounding
    border_size = 0
    rotate = 0
    reload_time = 0
    reload_cmd =
    position = 0, 420
    halign = center
    valign = bottom
    shadow_passes = 2
    shadow_size = 3
    shadow_boost = 1.5

    border_color = rgba($c7.r, $c7.g, $c7.b, 0.60)
} 
