# Ported from mahaveergurjar/Hyprlock-Dots layout5.conf

 
$fn_greet=echo "Hi $USER"
$fn_splash=echo "$(hyprctl splash)"

background {
    monitor =
    path = $BACKGROUND_PATH
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = rgba($tone.c5.72.135.r, $tone.c5.72.135.g, $tone.c5.72.135.b, 0.90)
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = rgba($tone.c4.63.95.r, $tone.c4.63.95.g, $tone.c4.63.95.b, 0.90)
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] $fn_greet
    color = rgba($tone.c4.73.98.r, $tone.c4.73.98.g, $tone.c4.73.98.b, 0.90)
    font_size = 30
    position = 0, 100
    halign = center
    valign = center
    font_family = $font
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba($tone.c5.72.135.r, $tone.c5.72.135.g, $tone.c5.72.135.b, 0.60)
    inner_color = rgba($tone.c4.36.109.r, $tone.c4.36.109.g, $tone.c4.36.109.b, 0.60)
    font_color = rgba($fg.r, $fg.g, $fg.b, 0.90)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <span size="$ph.175.12.7382fa37"><i>  Logged in as </i>$USER</span>
    hide_input = false
    rounding = -1
    check_color = rgba($accent1_2ff)
    fail_color = rgba($tone.c1.55.204.r, $tone.c1.55.204.g, $tone.c1.55.204.b, 0.60)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = true
    position = 0, 0
    halign = center
    valign = center
    font_family = $font
}

label {
    monitor = 
    text = cmd[update:1000] $fn_splash
    text_align = right
    color = rgba($tone.c5.78.125.r, $tone.c5.78.125.g, $tone.c5.78.125.b, 0.90)
    font_family = $font, Font Awesome 20
    position = 0, 15
    halign = center
    valign = bottom
}

