# Ported from mahaveergurjar/Hyprlock-Dots layout10.conf
$wall = $BACKGROUND_PATH

# $wall = $HOME/.config/hyprlock/wallpapers/hyprlock.png
# source = $HOME/.config/hyprlock/fonts/SF Pro Display Bold
# BACKGROUND
background {
    monitor =
    path = $BACKGROUND_PATH
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Profie-Photo
image {
    monitor =
    path = $PROFILE_IMAGE
    border_size = 2
    border_color = rgba($tone.c4.59.137.r, $tone.c4.59.137.g, $tone.c4.59.137.b, 0.60) 
    size = 120
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 25, 190
    halign = center
    valign = center
}

# NAME
label {
    monitor =
    text = $USER
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 20
    font_family = $font Bold
    position = 25, 80
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    font_size = 60
    font_family = $font Bold
    position = 30, -20
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    font_size = 19
    font_family = $font Bold
    position = 35, -90
    halign = center
    valign = center
}


# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba($fg.r, $fg.g, $fg.b, 0.10)
    rounding = -1
    border_size = 0
    border_color = rgba($fg.r, $fg.g, $fg.b, 0.60)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 34, -190
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = cmd[update:0] printf '%s' '    $USER' | $HOME/.local/lib/hypr/session/hyprlock.fit.sh 284 55 16 $font Bold
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = $font Bold
    position = 38, -190
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba($fg.r, $fg.g, $fg.b, 0.00)
    inner_color = rgba($fg.r, $fg.g, $fg.b, 0.10)
    font_color = rgba($c7.r, $c7.g, $c7.b, 1.00)
    fade_on_empty = false
    font_family = $font Bold
    placeholder_text = <span size="$ph.292.13.d6fa8974"><i><span foreground="##$fg.hex" alpha="60%">   Enter Pass</span></i></span>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
}
