# Ported from mahaveergurjar/Hyprlock-Dots layout17.conf

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    disable_loading_bar = false
    hide_cursor = true
    immediate_render = true
}

# BACKGROUND
background {
    monitor =
    # path = $BACKGROUND_PATH
    color = rgba($bg.r, $bg.g, $bg.b, 1.00)
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}



# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d - %I:%M")"
    color = rgba($c7.r, $c7.g, $c7.b, 1.00)
    font_size = 15
    position = 0, 500
    halign = center
    valign = center
    font_family = $font
}


 

# Authenticate box
shape {
    monitor =
    size = 500, 100
    color =rgba($bg.r, $bg.g, $bg.b, 0.00)
    rounding = $rounding
    border_size = 2
    border_color = rgba($fg.r, $fg.g, $fg.b, 0.60)
    rotate = 0
    position = 0, 0
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 200, 20
    color =rgba($bg.r, $bg.g, $bg.b, 0.60)
    rounding = $rounding
    border_size = 2
    border_color = rgba($bg.r, $bg.g, $bg.b, 0.60)
    rotate = 0
    position = -130, 50
    halign = center
    valign = center
    zindex = 5
}

# USER
label {
    monitor =
    text =  cmd[update:0] printf '%s' 'Authenticate into archlinux' | $HOME/.local/lib/hypr/session/hyprlock.fit.sh 192 24 11 $font
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    font_size = 11
    position = -130, 50
    halign = center
    valign = center
    zindex = 5
    font_family = $font
}

# USER
label {
    monitor =
    text = cmd[update:0] printf '%s' '<b>  Username: $USER </b>' | $HOME/.local/lib/hypr/session/hyprlock.fit.sh 172 74 11 $font
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    font_size = 11
    position = -150 , 15
    halign = center
    valign = center
    zindex = 1
    font_family = $font
}

# USER
label {
    monitor =
    text = cmd[update:0] printf '%s' '<b> Password: </b>' | $HOME/.local/lib/hypr/session/hyprlock.fit.sh 92 74 11 $font
    color = rgba($c7.r, $c7.g, $c7.b, 0.80)
    font_size = 11
    position = -190, -15
    halign = center
    valign = center
    zindex = 5
    font_family = $font
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = -1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgba($bg.r, $bg.g, $bg.b, 0.00)
    inner_color =rgba($bg.r, $bg.g, $bg.b, 0.00)
    font_color = rgba($fg.r, $fg.g, $fg.b, 1.00)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 800 , -15
    halign = left
    valign = center
    font_family = $font
}


# NOTIFICATION
label {
    monitor =
    text =
    color = rgba($fg.r, $fg.g, $fg.b, 0.90)
    font_size = 14
    position = 0, 400
    halign = center
    valign = center
    zindex = 10
    font_family = $font
}
