wireplumber.components = [
  {
    name = switch-on-connect.lua, type = script/lua
    provides = custom.switch-on-connect
    requires = [ metadata.default ]
  }
]

wireplumber.profiles = {
  main = {
    custom.switch-on-connect = required
  }
}
