#!/usr/bin/env bash

status="$(playerctl status 2>/dev/null)"
if [[ "$status" == "Playing" || "$status" == "Paused" ]]; then
  playerctl metadata --format '#[fg=#{@theme_gray}] 󰽯 #[default,italics]{{title}}#[fg=#{@theme_gray}]  ' 2>/dev/null
fi
